export interface NewsItem {
  id: string;
  date: string; // YYYY-MM-DD
  title: string;
  summary: string;
  body: string; // HTML-safe plain text with line breaks
  category: "eapcet" | "fees" | "counselling" | "naac-nirf" | "general";
  state: "AP" | "TS" | "Both";
  priority: "high" | "medium" | "low";
  source?: string;
  sourceUrl?: string;
  tags: string[];
}

export const NEWS_ITEMS: NewsItem[] = [
  // ── New: June 21, 2026 ───────────────────────────────────────
  {
    id: "ap-eapcet-2026-result-expected-end-june-21",
    date: "2026-06-21",
    title: "AP EAPCET 2026 Result Now Expected by End of June — Officials Awaiting CBSE Revised Marks",
    summary: "AP EAPCET 2026 rank cards are still not declared as of June 21. APSCHE officials are now waiting on CBSE revised (re-evaluation) Class XII results before finalising ranks, since Intermediate marks carry 25% weightage in the EAPCET rank formula. Press reports (Eenadu, June 21) indicate the rank cards are now expected by the end of June 2026 at cets.apsche.ap.gov.in. No official date has been notified — treat all dates as tentative until APSCHE confirms.",
    body: "As of June 21, 2026, the Andhra Pradesh State Council of Higher Education (APSCHE) has still not released the AP EAPCET 2026 rank cards. The result was originally scheduled for June 1, then expected in the June 18–21 window, and is now reported to be pushed to the end of June.\n\nWhy the further delay:\n• The final EAPCET rank combines the entrance score (75%) with Intermediate (Class XII) marks (25%), so APSCHE needs every candidate's final Class XII marks before locking ranks.\n• Officials are now waiting for the CBSE revised / re-evaluation Class XII results to be factored in for CBSE-stream candidates.\n• Marks verification for the AP Intermediate supplementary/improvement exams concluded around June 7, and a small number of candidate grievances were still being resolved.\n• With these inputs pending, press reports (Eenadu, June 21, 2026) indicate the rank cards are now expected by the end of June 2026. APSCHE has not notified an exact official date.\n\nContext: Around 3.29 lakh+ candidates are awaiting the result. AP EAPCET ranks drive admission into B.Tech/B.E, B.Pharmacy, and Agriculture/Pharmacy courses across Andhra Pradesh for 2026–27.\n\nHow to check your result once it goes live:\n1. Visit cets.apsche.ap.gov.in and open EAPCET 2026 → Results / Rank Card\n2. Log in with your hall ticket number and date of birth (or registration number)\n3. Download and save the PDF rank card; take 2–3 printouts for counselling\n\nWhat to do now: Keep your hall ticket, date of birth and counselling certificates (income, caste, study/Transfer Certificate) ready, and build your college preference list using your expected rank so you can enter web options quickly once counselling opens (expected July 2026). Treat all dates as tentative until APSCHE publishes the official notification.",
    category: "eapcet",
    state: "AP",
    priority: "high",
    source: "Eenadu / APSCHE — AP EAPCET 2026 result status (June 21)",
    sourceUrl: "https://cets.apsche.ap.gov.in/EAPCET/",
    tags: ["AP EAPCET", "Result", "Expected", "End of June", "CBSE", "2026"],
  },
  // ── New: June 20, 2026 ───────────────────────────────────────
  {
    id: "ap-eapcet-2026-result-awaited-june-20",
    date: "2026-06-20",
    title: "AP EAPCET 2026 Result Still Awaited — Now Expected Around June 22–23",
    summary: "AP EAPCET 2026 rank cards are still not out as of June 20. The AP Intermediate supplementary/improvement results — the dependency for the 25% Class XII weightage in the rank formula — were declared on June 18, so final ranks can now be computed. APSCHE has not notified an official date, but education-department and press sources now point to June 22–23, 2026 at cets.apsche.ap.gov.in.",
    body: "As of June 20, 2026, the Andhra Pradesh State Council of Higher Education (APSCHE) has still not released the AP EAPCET 2026 rank cards. The result was originally scheduled for June 1 and then expected in the June 18–21 window.\n\nWhat has changed:\n• The AP Intermediate Advanced Supplementary / Improvement results — which carry 25% weightage in the final EAPCET rank — were declared by BIEAP on June 18, 2026.\n• With the updated Intermediate marks now available, APSCHE can finalise the 75% EAPCET + 25% Inter rank computation for all candidates.\n• APSCHE has not yet notified an exact official date. Education-department and press sources now indicate the rank cards are expected around June 22–23, 2026.\n\nHow to check your result once it goes live:\n1. Visit cets.apsche.ap.gov.in and open EAPCET 2026 → Results / Rank Card\n2. Log in with your hall ticket number and date of birth (or registration number)\n3. Download and save the PDF rank card; take 2–3 printouts for counselling\n\nWhat to do now: Keep your hall ticket, date of birth and counselling certificates (income, caste, study/Transfer Certificate) ready, and build your college preference list using your expected rank so you can enter web options quickly once counselling opens (expected early July 2026). Treat all dates as expected until APSCHE publishes the official notification.",
    category: "eapcet",
    state: "AP",
    priority: "high",
    source: "APSCHE / JNTU Kakinada — AP EAPCET 2026 result status (June 20)",
    sourceUrl: "https://cets.apsche.ap.gov.in/EAPCET/",
    tags: ["AP EAPCET", "Result", "Expected", "June 22", "June 23", "2026"],
  },
  // ── New: June 18, 2026 ───────────────────────────────────────
  {
    id: "ap-inter-supplementary-results-2026-june-18",
    date: "2026-06-18",
    title: "AP Inter 1st & 2nd Year Supplementary (IPASE) Results 2026 Declared — Check at bie.ap.gov.in",
    summary: "BIEAP declared the AP Intermediate Advanced Supplementary (IPASE) results 2026 for both 1st and 2nd year on June 18, 2026 at 12:00 PM at bie.ap.gov.in and resultsbie.ap.gov.in. Candidates check the marks memo with their 10-digit hall ticket number. These exams were the second chance for students who did not clear one or more subjects in the regular IPE, whose results were declared on April 15 (1st year 77%, 2nd year 81%).",
    body: "The Board of Intermediate Education, Andhra Pradesh (BIEAP) declared the AP Intermediate Public Advanced Supplementary Examination (IPASE) results 2026 for both 1st year and 2nd year on June 18, 2026 at 12:00 PM at bie.ap.gov.in and resultsbie.ap.gov.in.\n\nKey points:\n• Supplementary (IPASE) exams: May 21 – June 4, 2026 (papers postponed from May 28 — Economics Paper-I, Maths Paper-IIB and the Vocational Bridge Course — were held on June 5)\n• Practical examinations: June 7 – June 11, 2026\n• Result declared: June 18, 2026 at 12:00 PM\n• Login: 10-digit hall ticket number (date of birth may also be required)\n\nHow to check your AP Inter supplementary result 2026:\n1. Visit bie.ap.gov.in or resultsbie.ap.gov.in\n2. Click the \"AP Inter 1st / 2nd Year Supplementary Result 2026\" link under the Results section\n3. Enter your 10-digit hall ticket number (and date of birth if prompted)\n4. Submit — your subject-wise marks, total and pass/fail status will display\n5. Download and print the marks memo for admissions and verification\n\nAlternative ways to check: BIEAP WhatsApp service (send \"Hi\" to 9552300009), DigiLocker for the digital marks memo, and mirror portals bieap.apcfss.in and Manabadi if the official site is busy.\n\nPassing criteria: A minimum of 35% (35/100) is required in each subject, in both theory and practical components where applicable.\n\nContext — the regular IPE 2026 results: The main Intermediate results were declared on April 15, 2026, with a first-year pass percentage of 77% (5,31,275 students appeared) and a second-year pass percentage of 81% (5,26,264 students appeared). The supplementary examination gave students who missed the cut-off in one or more subjects a chance to clear them without losing an academic year.\n\nWhat candidates should do now: Download and save the supplementary marks memo immediately. Students who have now cleared 2nd year are eligible to proceed with higher-education admissions and entrance-based counselling (including AP EAPCET). Candidates not satisfied with their marks can apply for recounting or revaluation per the separate BIEAP notification. The original physical marks memo is issued later through colleges.",
    category: "general",
    state: "AP",
    priority: "high",
    source: "BIEAP — AP Inter Advanced Supplementary (IPASE) Results 2026",
    sourceUrl: "https://resultsbie.ap.gov.in/",
    tags: ["AP Inter", "Intermediate", "IPASE", "Supplementary", "BIEAP", "Result", "June 18", "2026"],
  },
  // ── New: June 13, 2026 ───────────────────────────────────────
  {
    id: "josaa-2026-round-1-allotment-june-13",
    date: "2026-06-13",
    title: "JoSAA 2026 Round 1 Seat Allotment Released — Check Result at josaa.nic.in",
    summary: "JoSAA 2026 Round 1 seat allotment was released on June 13, 2026 at 10:00 AM at josaa.nic.in. Candidates allotted a seat must choose Freeze, Float, or Slide and complete online financial commitment (reporting fee) before June 26. Round 2 allotment is on June 30.",
    body: "The Joint Seat Allocation Authority (JoSAA) released the Round 1 seat allotment result for 2026 on June 13, 2026 at 10:00 AM at josaa.nic.in, covering 138 institutes — 23 IITs, IISc Bengaluru, 31 NITs, IIEST Shibpur, 26 IIITs and 56 GFTIs — for 67,323 total seats (4,470 more than 2025).\n\nHow to check your allotment:\n1. Visit josaa.nic.in\n2. Log in with your JEE 2026 Main application number and password\n3. Your allotted institute, programme and category will display\n4. Download and save the allotment letter\n\nWhat to do after Round 1 allotment:\n• Freeze: Accept the seat permanently and opt out of subsequent rounds (best option if you're happy with the allotment)\n• Float: Accept the current seat but remain in the pool for upgrades to a higher preference in the next round at the same or a different institute\n• Slide: Accept the current seat but seek an upgrade to a higher-preferred programme within the same institute only\n\nOnline financial commitment (reporting fee): Mandatory during the June 13–26 window to lock any Round 1 seat.\n• General/OBC-NCL/EWS: ₹35,000\n• SC/ST/PwD: ₹15,000\n(Adjustable against tuition fee after final allotment)\n\nRemaining round schedule:\n• Round 2 allotment: June 30, 2026\n• Round 3 allotment: July 6, 2026\n• Round 4 allotment: July 10, 2026\n• Round 5 allotment: July 16, 2026 (final JoSAA round)\n\nFor AP/TS aspirants: IIT Hyderabad is the most popular IIT for Telugu-state candidates. NIT Warangal (TS) and NIT Andhra Pradesh (Tadepalligudem) participate via JEE Main rank. IIIT Hyderabad (UGEE-based) and IIIT Sri City fill seats outside JoSAA through separate processes.\n\nDocuments to keep ready for online reporting: Class X and XII marksheets, Aadhaar/photo ID, category certificate (OBC-NCL/SC/ST/EWS in JoSAA format), PwD certificate if applicable, JEE Main and JEE Advanced scorecards, and passport-size photograph matching the application.",
    category: "counselling",
    state: "Both",
    priority: "high",
    source: "Joint Seat Allocation Authority (JoSAA) 2026",
    sourceUrl: "https://josaa.nic.in/",
    tags: ["JoSAA", "IIT", "NIT", "IIIT", "Round 1", "Seat Allotment", "June 13", "2026"],
  },
  // ── New: June 12, 2026 ───────────────────────────────────────
  {
    id: "tg-icet-2026-result-declared-june-12",
    date: "2026-06-12",
    title: "TG ICET 2026 Result Declared — Rank Cards Live at icet.tgche.ac.in",
    summary: "TGCHE declared the TG ICET 2026 result (MBA/MCA admissions) on June 12, 2026 at 3:30 PM at icet.tgche.ac.in — one week ahead of the originally announced June 19 date. Rank cards are now live. Counselling is expected to begin a few weeks after the result.",
    body: "The Telangana Council of Higher Education (TGCHE) declared the TG ICET 2026 result on June 12, 2026 at 3:30 PM at icet.tgche.ac.in — preponed from the originally announced June 19 date after swift resolution of candidate objections.\n\nKey points:\n• Exam conducted: May 13–14, 2026 (CBT mode)\n• Preliminary answer key: Released May 29, 2026\n• Objection window: May 30 – June 5, 2026 (closed)\n• Result declared: June 12, 2026 at 3:30 PM at icet.tgche.ac.in\n• Rank card download: Hall ticket number + registration number + date of birth\n\nHow to download your rank card:\n1. Visit icet.tgche.ac.in\n2. Click the \"Download Rank Card\" link\n3. Enter ICET Hall Ticket Number, Registration Number and Date of Birth\n4. Click \"View Rank Card\" — normalised scores, section-wise marks and state rank will display\n5. Download the PDF and take printouts\n\nQualifying marks: General/OBC candidates must score a minimum 25% (50/200 marks). No minimum qualifying marks for SC/ST candidates.\n\nWhat TG ICET scores are used for: Admission into MBA and MCA programmes in university and affiliated colleges across Telangana for 2026–27. Seat allocation happens through TGCHE's online ICET counselling (registration, certificate verification, web options, seat allotment) — expected to be notified a few weeks after the result. Track icet.tgche.ac.in for the counselling schedule.\n\nWhat candidates should do now: Download and save your rank card. Keep certificates ready for counselling — SSC, Intermediate, degree memos, Transfer Certificate, study certificates, and caste/income/EWS certificates as applicable.",
    category: "general",
    state: "TS",
    priority: "high",
    source: "TGCHE — TG ICET 2026 Result Declaration",
    sourceUrl: "https://icet.tgche.ac.in/",
    tags: ["TG ICET", "TS ICET", "Result", "MBA", "MCA", "June 12", "2026"],
  },
  // ── New: June 9, 2026 ─────────────────────────────────────────
  {
    id: "tg-eapcet-2026-counselling-schedule-june-19",
    date: "2026-06-09",
    title: "TG EAPCET 2026 Engineering Counselling Schedule Notified — Registration June 19–28; Web Options June 25–July 1",
    summary: "TGCHE has notified the TG EAPCET 2026 engineering admission schedule. Online registration and certificate-verification slot booking run June 19–28, 2026 at tgeapcet.nic.in. Certificate verification: June 22–29. Web options: June 25–July 1. Mock seat allocation by July 4; first-phase seat allotment on or before July 10. Processing fee ₹1,200 (OC/BC) / ₹600 (SC/ST).",
    body: "The Telangana Council of Higher Education (TGCHE) has notified the TG EAPCET 2026 engineering (E-stream) admission counselling schedule. The process is conducted online at tgeapcet.nic.in in three phases plus internal sliding and spot admissions.\n\nFirst-phase schedule:\n• Online registration + processing-fee payment + slot booking: June 19 – June 28, 2026\n• Certificate verification (at Help Line Centres, per slot): June 22 – June 29, 2026\n• Web options (college/branch preferences): June 25 – July 1, 2026\n• Mock seat allocation: on or before July 4, 2026\n• Web option modification (after mock allotment): July 5 – July 7, 2026\n• First-phase seat allotment: on or before July 10, 2026\n• Tuition-fee payment + online self-reporting (Phase 1): until July 14, 2026\n• Subsequent phases (web options, allotment, fee payment, reporting, internal sliding): through mid-August 2026\n\nProcessing fee:\n• OC / BC: ₹1,200\n• SC / ST: ₹600\n\nDocuments to keep ready (originals + scans for verification): TG EAPCET 2026 rank card and hall ticket, SSC (Class X) memo, Intermediate (Class XII) memos, Transfer Certificate, study/bonafide certificates (Classes VI–XII for local-area status), Aadhaar, income certificate (for fee reimbursement / tuition-fee eligibility), caste certificate (if applicable), and EWS certificate (if applicable).\n\nFee context: Convenor-quota tuition fees for the 2025–26 to 2027–28 block are fixed under G.O. Ms. No. 06 dt. 04.03.2026 (TAFRC), ₹45,000 floor and ₹1,83,000 ceiling (CBIT). The government fee-reimbursement scheme covers convenor-quota tuition for eligible candidates as per current policy.\n\nWhat candidates should do now: Pay the processing fee and book a certificate-verification slot early in the June 19–28 window to secure a convenient Help Line Centre and date. Track tgeapcet.nic.in and eapcet.tgche.ac.in for any revision to the allotment dates.",
    category: "counselling",
    state: "TS",
    priority: "high",
    source: "TGCHE / JNTU Hyderabad — TG EAPCET 2026 Engineering Counselling Notification",
    sourceUrl: "https://eapcet.tgche.ac.in/",
    tags: ["TG EAPCET", "TS EAMCET", "Counselling", "Registration", "June 19", "2026"],
  },
  // ── New: June 4, 2026 ─────────────────────────────────────────
  {
    id: "ap-eapcet-2026-result-postponed-june-17",
    date: "2026-06-04",
    title: "AP EAPCET 2026 Result Postponed Beyond Original June 1 Date",
    summary: "APSCHE has postponed the AP EAPCET 2026 result from the originally announced June 1 date. Rank cards are now expected between June 18 and June 21, after the AP Intermediate Advanced Supplementary and Improvement results are declared. The delay protects the 25% Class XII weightage in the EAPCET rank formula.",
    body: "The Andhra Pradesh State Council of Higher Education (APSCHE) has officially postponed the AP EAPCET 2026 result declaration. The result was originally scheduled for June 1, 2026 but is now expected to be released between June 18 and June 21, 2026 at cets.apsche.ap.gov.in.\n\nWhy the delay?\n• Class XII (Intermediate) marks carry 25% weightage in the final AP EAPCET rank formula\n• Approximately 1.50 lakh second-year Intermediate students are currently writing the BIEAP Advanced Supplementary and Improvement examinations\n• Around 1 lakh of them are attempting the Mathematics paper to improve their score\n• Supplementary/Improvement exams conclude on June 5, 2026; results follow soon after\n• Declaring EAPCET ranks before the updated Inter marks are in would create an unfair rank for these students\n\nRevised expected timeline:\n• AP Intermediate Advanced Supplementary / Improvement exams: through June 5, 2026 (BIEAP)\n• BIEAP supplementary results: shortly after June 5\n• AP EAPCET 2026 final answer key + ranks: expected June 18, 2026 onwards\n• AP EAPCET 2026 rank cards available: expected by June 21, 2026\n• AP EAPCET 2026 counselling notification: expected first week of July 2026 (no change so far)\n\nThe final answer key — incorporating all valid objections submitted before the 11 AM, May 27 deadline — will be published alongside the result.\n\nWhat candidates should do now: Keep your hall ticket, response sheet and saved provisional key safe. Track cets.apsche.ap.gov.in for the official notification of the new result date. Counselling timelines (early July) remain unchanged for now.",
    category: "eapcet",
    state: "AP",
    priority: "high",
    source: "APSCHE / JNTU Kakinada — AP EAPCET 2026 Result Postponement",
    sourceUrl: "https://cets.apsche.ap.gov.in/EAPCET/",
    tags: ["AP EAPCET", "Result", "Postponed", "June 17", "June 21", "2026"],
  },
  // ── New: June 4, 2026 ─────────────────────────────────────────
  {
    id: "ts-lawcet-2026-result-declared-june-4",
    date: "2026-06-04",
    title: "TS LAWCET & PGLCET 2026 Results Declared — Rank Cards Live at lawcet.tgche.ac.in",
    summary: "Osmania University, on behalf of TGCHE, declared the TS LAWCET and TS PGLCET 2026 results on June 4, 2026 at lawcet.tgche.ac.in. Of 54,374 candidates who appeared, 39,672 qualified. Meesala Vijayadurga topped the 3-Year LLB and Alluri Sanith Reddy the 5-Year LLB. Counselling for LLB/LLM admissions will be notified at lawcetadm.tgche.ac.in.",
    body: "Osmania University, the conducting body on behalf of the Telangana Council of Higher Education (TGCHE), declared the TS LAWCET 2026 (3-Year and 5-Year LLB) and TS PGLCET 2026 (LLM) results on June 4, 2026 at lawcet.tgche.ac.in. The final answer key and topper list were published alongside the result.\n\nResult statistics:\n• Total applications received: 66,620\n• Candidates appeared: 54,374\n• Candidates qualified: 39,672\n\nToppers:\n• 3-Year LLB — Rank 1: Meesala Vijayadurga (Vizianagaram, Andhra Pradesh)\n• 5-Year LLB — Rank 1: Alluri Sanith Reddy (Medchal-Malkajgiri)\n• TS PGLCET (LLM) — Rank 1: Sheguri Nishitha (Rangareddy)\n\nQualifying marks: General/OBC candidates must score a minimum 35% — 42 out of 120 marks. There is no minimum qualifying mark for SC/ST candidates.\n\nHow to download your rank card:\n1. Visit lawcet.tgche.ac.in\n2. Click the \"TS LAWCET Result 2026\" link\n3. Enter your Hall Ticket Number, Registration Number and Date of Birth\n4. Submit — your marks, rank, category and qualifying status will display\n5. Download the rank card and take printouts for counselling\n\nWhat happens next — counselling: Qualified candidates are eligible for admission to 3-Year LLB and 5-Year integrated LLB programmes (and LLM via PGLCET) across Telangana law colleges. The detailed counselling schedule will be notified at lawcetadm.tgche.ac.in. The process includes online registration, counselling-fee payment, certificate verification, web options and seat allotment.\n\nCounselling fee: ₹800 (General/OBC) and ₹500 (SC/ST).\n\nDocuments to keep ready: TS LAWCET rank card and hall ticket, SSC (Class X) and Intermediate memos, degree certificate (for LLB/LLM as applicable), Transfer Certificate, study certificates, Aadhaar, and caste/income/EWS certificates if applicable. Track lawcetadm.tgche.ac.in for the counselling notification.",
    category: "general",
    state: "TS",
    priority: "medium",
    source: "TGCHE / Osmania University — TS LAWCET & PGLCET 2026 Result Declaration",
    sourceUrl: "https://lawcet.tgche.ac.in/",
    tags: ["TS LAWCET", "TG LAWCET", "PGLCET", "Result", "LLB", "LLM", "June 4", "2026"],
  },
  // ── New: June 2, 2026 ─────────────────────────────────────────
  {
    id: "jee-advanced-2026-result-declared-june-1",
    date: "2026-06-02",
    title: "JEE Advanced 2026 Result Declared — Shubham Kumar AIR 1 (330/360); 56,880 Qualify",
    summary: "IIT Roorkee declared the JEE Advanced 2026 result on June 1 at 2:45 AM at jeeadv.ac.in. Shubham Kumar (IIT Delhi zone) topped with AIR 1 and 330/360. Kabeer Chhillar (329) and Jatin Chahar (319) followed at AIR 2 and 3. Female topper: Arohi Deshpande (AIR 77, 280/360). 56,880 of 1,79,694 appeared candidates qualified.",
    body: "IIT Roorkee, the organising institute for JEE Advanced 2026, declared the result on Monday, June 1, 2026 at 2:45 AM IST at jeeadv.ac.in.\n\nOverall toppers:\n• AIR 1: Shubham Kumar — 330/360 (IIT Delhi zone)\n• AIR 2: Kabeer Chhillar — 329/360\n• AIR 3: Jatin Chahar — 319/360\n• Female topper (overall): Arohi Deshpande — AIR 77, 280/360\n\nKey statistics:\n• Candidates registered: 1,87,389\n• Candidates appeared in both papers: 1,79,694\n• Candidates qualified for JoSAA counselling: 56,880\n• Female qualifiers: 10,107\n\nNext steps:\n• Final answer key: Published alongside the result on jeeadv.ac.in\n• Scorecard download: Available on the candidate portal (registration number + DOB / password)\n• JEE Advanced AAT (Architecture Aptitude Test) registration: Opened June 1, closed June 2 at 5 PM — exam on June 4, 2026\n• JoSAA 2026 counselling registration: Opened June 2, 2026 at 5 PM at josaa.nic.in — runs in 5 rounds (Round 1 allotment on June 13)\n\nFor AP/TS aspirants: All 56,880 qualified candidates are eligible to participate in JoSAA 2026 counselling for IIT seat allocation. IIT Hyderabad remains the most popular IIT for Telugu-state candidates, followed by IIT Madras, Bombay and Roorkee. Carry the Class X / XII marksheets, photo ID, category and PwD certificates (if applicable) to round-wise online reporting.",
    category: "general",
    state: "Both",
    priority: "high",
    source: "JEE (Advanced) 2026 — IIT Roorkee Result Declaration",
    sourceUrl: "https://jeeadv.ac.in/",
    tags: ["JEE Advanced", "IIT Roorkee", "Result", "Shubham Kumar", "Toppers", "AIR 1", "2026"],
  },
  {
    id: "jee-aat-2026-exam-june-4",
    date: "2026-06-02",
    title: "JEE Advanced AAT 2026 — Result Declared June 7; Qualifiers Move to JoSAA B.Arch Counselling",
    summary: "IIT Roorkee conducted the JEE Advanced AAT (Architecture Aptitude Test) 2026 on June 4 (9 AM–12 noon) and declared the result on June 7, 2026 at jeeadv.ac.in. Qualified candidates are now eligible for B.Arch admissions through JoSAA at IIT Kharagpur, IIT Roorkee and IIT (BHU) Varanasi.",
    body: "IIT Roorkee opened the JEE Advanced AAT 2026 registration on Sunday, June 1, 2026 immediately after the JEE Advanced result was declared. Registration closed on Tuesday, June 2 at 5:00 PM IST.\n\n• Registration window: June 1 – June 2, 2026 (5 PM close) at jeeadv.ac.in\n• Exam date: June 4, 2026 (9:00 AM – 12:00 noon)\n• Exam duration: 3 hours (Free-hand drawing, geometric drawing, three-dimensional perception, imagination & aesthetic sensitivity, architectural awareness)\n• Result: Declared June 7, 2026 at jeeadv.ac.in (Qualified / Not Qualified status)\n• Admit card: Not separately issued — candidates must carry the printed JEE Advanced 2026 admit card + valid original photo ID to the AAT exam centre\n\nEligibility: Only candidates who appeared in JEE Advanced 2026 (both papers) and qualified are eligible to register for AAT.\n\nWhere AAT scores are used: B.Arch programme admissions at IIT Kharagpur, IIT Roorkee and IIT (BHU) Varanasi. AAT qualifying status is reported as Qualified / Not Qualified — actual seat allocation happens through JoSAA 2026 counselling on the basis of JEE Advanced rank.\n\nFor AP/TS aspirants targeting B.Arch at an IIT, AAT is the mandatory next gate after JEE Advanced.",
    category: "general",
    state: "Both",
    priority: "medium",
    source: "JEE (Advanced) 2026 — IIT Roorkee AAT 2026 Notice",
    sourceUrl: "https://jeeadv.ac.in/",
    tags: ["JEE AAT", "Architecture Aptitude Test", "IIT Roorkee", "B.Arch", "June 4", "2026"],
  },
  // ── New: May 29, 2026 ─────────────────────────────────────────
  {
    id: "re-neet-2026-city-slip-may-31-admit-card-june-14",
    date: "2026-05-29",
    title: "Re-NEET 2026 — City Intimation Slip Released; Admit Card Expected June 14",
    summary: "NTA has released the Re-NEET 2026 city intimation slip at neet.nta.nic.in, letting candidates plan travel ahead of the June 21 re-exam. The admit card (with the exact centre address) is expected on June 14. The re-exam runs 2:00–5:15 PM for all 22.79 lakh candidates affected by the May 3 paper-leak cancellation.",
    body: "The National Testing Agency (NTA) has released the Re-NEET UG 2026 city intimation slip at neet.nta.nic.in — roughly three weeks ahead of the re-exam. The advance city slip lets candidates plan travel and accommodation; the actual exam centre address is shared only on the admit card.\n\nKey dates:\n• City intimation slip: Released at neet.nta.nic.in (shows allotted city only, not the exact centre)\n• Admit card release: Expected June 14, 2026 (carries the exact exam-centre address)\n• Re-exam (Re-NEET 2026): June 21, 2026 (Saturday)\n• Exam timing: 2:00 PM – 5:15 PM (15 minutes extra vs the original NEET UG)\n• Mode: Pen-and-paper\n• Fee refund window (for candidates not appearing in the re-exam): Extended to June 22, 2026\n\nBackground: NTA cancelled the May 3, 2026 NEET UG exam after a CBI-confirmed paper leak. All 22,79,743 originally registered candidates are eligible for Re-NEET 2026. The re-exam is being held in pen-and-paper mode at NTA-designated centres across India.\n\nHow to download the city slip:\n1. Visit neet.nta.nic.in\n2. Click the advance city intimation link for Re-NEET 2026\n3. Log in with application number + DOB / password\n4. Download and save the slip — it shows only the allotted city, not the exact centre\n\nFor AP/TS aspirants: NEET UG 2026 scores remain the sole criterion for MBBS/BDS admissions at Dr. NTR UHS (AP) and KNRUHS (Telangana), plus 15% AIQ (MCC) and deemed universities. State counselling is now expected to begin in late July / August 2026, after the Re-NEET result.\n\nFrom 2027 onwards, NEET UG will shift to Computer-Based Test (CBT) mode to prevent paper leaks, as announced by the Union Education Minister.",
    category: "general",
    state: "Both",
    priority: "high",
    source: "NTA — Re-NEET 2026 City Intimation / Admit Card Notice",
    sourceUrl: "https://neet.nta.nic.in/",
    tags: ["NEET UG", "Re-NEET", "City Intimation", "Admit Card", "NTA", "June 21", "2026"],
  },
  {
    id: "tg-ecet-2026-results-declared-may-29",
    date: "2026-05-29",
    title: "TG ECET 2026 Results Declared — Rank Cards Live at ecet.tgche.ac.in",
    summary: "TGCHE declared the TG ECET 2026 results on May 29, 2026 at 3:30 PM. Rank cards are available at ecet.tgche.ac.in (hall ticket number + registration number + date of birth). TG ECET ranks are used for lateral-entry (second-year) admission into B.E./B.Tech and B.Pharmacy for diploma and B.Sc (Maths) holders. Counselling notification expected in June/July 2026.",
    body: "The Telangana Council of Higher Education (TGCHE) formally declared the TG ECET 2026 results and rank cards on May 29, 2026 at 3:30 PM at ecet.tgche.ac.in.\n\nKey points:\n• Exam conducted: May 15, 2026 (CBT mode)\n• Preliminary answer key: May 20, 2026; objections reviewed before final key\n• Results + rank cards: Declared May 29, 2026 at ecet.tgche.ac.in\n• Rank card download: Hall ticket number + registration number + date of birth\n\nWhat TG ECET ranks are used for: Lateral-entry admission directly into the second year of B.E./B.Tech and B.Pharmacy programmes in Telangana for diploma holders (Engineering/Pharmacy) and B.Sc (Mathematics) graduates.\n\nNext step — counselling: TGCHE's online web counselling (registration, certificate verification, web options, seat allotment) is expected to be notified in June/July 2026. Track ecet.tgche.ac.in for the schedule.\n\nWhat candidates should do now: Download and save the rank card, and keep certificates ready for verification — diploma/degree memos, SSC memo, Transfer Certificate, study certificates, Aadhaar, and income/caste/EWS certificates as applicable.",
    category: "general",
    state: "TS",
    priority: "medium",
    source: "TGCHE — TG ECET 2026 Results Declaration",
    sourceUrl: "https://ecet.tgche.ac.in/",
    tags: ["TG ECET", "TS ECET", "Results", "Rank Card", "Lateral Entry", "May 29", "2026"],
  },
  // ── New: May 27, 2026 ─────────────────────────────────────────
  {
    id: "josaa-2026-registration-opens-june-2",
    date: "2026-05-27",
    title: "JoSAA 2026 — IIT/NIT/IIIT/GFTI Counselling Registration Opens June 2 (5 PM); 5 Rounds, Last Date June 11",
    summary: "JoSAA 2026 counselling registration opens on June 2, 2026 at 5 PM at josaa.nic.in — one day after the JEE Advanced result. Five rounds across 138 institutes (23 IITs, IISc, 31 NITs, IIEST Shibpur, 26 IIITs and 56 GFTIs) for 67,323 seats. Registration + choice-filling close June 11. Round 1 allotment: June 13.",
    body: "The Joint Seat Allocation Authority (JoSAA) has confirmed the JEE Advanced 2026 schedule and opens JoSAA 2026 counselling registration on June 2, 2026 at 5:00 PM IST at josaa.nic.in — one day after the JEE Advanced 2026 result is declared on June 1.\n\nKey points:\n• Registration + choice-filling opens: June 2, 2026 at 5:00 PM\n• Registration + choice-filling closes: June 11, 2026\n• Total rounds: 5 (each round = seat allotment → online acceptance → online reporting + fee payment → document upload)\n• Participating institutes: 138 — 23 IITs + IISc Bengaluru + 31 NITs + IIEST Shibpur + 26 IIITs + 56 GFTIs (Other Government-Funded Technical Institutes)\n• Total seats offered: 67,323 (4,470 more than 2025)\n• Eligibility: JEE Main 2026 (any session) rank for NITs/IIITs/GFTIs; JEE Advanced 2026 qualified candidates (56,880 this year) for IITs\n• Reporting fee: ₹35,000 (general) / ₹15,000 (SC/ST/PwD) — adjustable against tuition fee after final allotment\n\nRound-wise schedule:\n• Mock allotment round 1: June 8, 2026\n• Mock allotment round 2: June 10, 2026\n• Round 1 seat allotment: June 13, 2026\n• Round 2 seat allotment: June 30, 2026\n• Round 3 seat allotment: July 6, 2026\n• Round 4 seat allotment: July 10, 2026\n• Round 5 seat allotment: July 16, 2026 (final JoSAA round; CSAB special rounds follow for left-over NIT+ seats)\n\nFor AP/TS aspirants:\n• IIT Hyderabad remains the most popular IIT for Telugu-state candidates, followed by IIT Madras, Bombay and Roorkee\n• NIT Warangal (TS) and NIT Andhra Pradesh (Tadepalligudem) participate via JEE Main rank\n• IIIT Hyderabad (UGEE-based) and IIIT Sri City fill seats outside JoSAA — separate processes\n\nDocuments to keep ready (scanned + originals for online reporting):\n• Class X and XII marksheets and pass certificates\n• Photo ID (Aadhaar preferred)\n• Category certificate (OBC-NCL / SC / ST / EWS) issued in the prescribed JoSAA format\n• PwD certificate (if applicable)\n• Passport-size photograph matching the application\n• JEE Main and (for IITs) JEE Advanced scorecards",
    category: "counselling",
    state: "Both",
    priority: "high",
    source: "Joint Seat Allocation Authority (JoSAA) / JEE (Advanced) 2026 — IIT Roorkee",
    sourceUrl: "https://josaa.nic.in/",
    tags: ["JoSAA", "IIT", "NIT", "IIIT", "GFTI", "Counselling", "JEE Advanced", "2026"],
  },
  // ── New: May 25, 2026 ─────────────────────────────────────────
  {
    id: "ap-eapcet-2026-preliminary-key-released-may-25",
    date: "2026-05-25",
    title: "AP EAPCET 2026 — Preliminary Answer Key Released; Objection Window Closes May 27 at 11 AM",
    summary: "JNTU Kakinada released the AP EAPCET 2026 preliminary answer key at 11 AM on May 25 at cets.apsche.ap.gov.in. Candidate response sheets were already live. Objections can be raised online until 11 AM on May 27, 2026. Final result: June 1, 2026.",
    body: "The Andhra Pradesh Engineering, Agriculture and Pharmacy Common Entrance Test (AP EAPCET) 2026 preliminary answer key has been released by JNTU Kakinada at 11:00 AM on May 25, 2026 at cets.apsche.ap.gov.in.\n\nKey points (per AP EAPCET-2026 convener Prof. N. Mohan Rao):\n• Preliminary key release: May 25, 2026 at 11:00 AM (revised from the earlier May 23 indication)\n• Candidate response sheets: Already uploaded on the official portal\n• Objection window: Open until May 27, 2026 at 11:00 AM\n• Objections accepted via: https://cets.apsche.ap.gov.in (login with hall ticket + DOB)\n• Final result + rank card: June 1, 2026\n\nThe AP EAPCET 2026 examination was conducted successfully in CBT mode from May 12 to May 20, 2026 across Andhra Pradesh and Hyderabad (Engineering: May 12, 13, 14, 15 & 18; Agriculture/Pharmacy: May 19–20), as confirmed by AP EAPCET 2026 chairman and JNTUK Vice-Chancellor Prof. C.S.R.K. Prasad.\n\nHow to raise an objection: Download the preliminary key and your response sheet from the candidate login, identify any disputed question, then submit the challenge via the \"Key Objections\" link with the question ID, a clear reason, and supporting evidence (textbook reference, derivation, etc.). APSCHE / JNTUK will review every objection before publishing the final answer key alongside the result on June 1.\n\nWhat to do now: Save your response sheet immediately, cross-check with the preliminary key, and file objections only with citable evidence before the 11 AM, May 27 deadline. AP EAPCET 2026 counselling is expected to start in the first week of July 2026 with two regular rounds plus a spot round, conducted by APSCHE.",
    category: "eapcet",
    state: "AP",
    priority: "high",
    source: "APSCHE / JNTU Kakinada — AP EAPCET 2026 Preliminary Key Notice (DC Correspondent, 23.05.2026)",
    sourceUrl: "https://cets.apsche.ap.gov.in/EAPCET/",
    tags: ["AP EAPCET", "Answer Key", "Preliminary Key", "Objections", "May 25", "2026"],
  },
  {
    id: "jee-advanced-2026-provisional-key-released-may-25",
    date: "2026-05-25",
    title: "JEE Advanced 2026 — Provisional Answer Key Released; Objections Open Till 5 PM, May 26",
    summary: "IIT Roorkee released the JEE Advanced 2026 provisional answer key for Paper 1 and Paper 2 at 10 AM on May 25 at jeeadv.ac.in. Candidates can raise objections until 5:00 PM on May 26, 2026. Final answer key and result: June 1, 2026 at 10 AM.",
    body: "IIT Roorkee, the organising institute for JEE Advanced 2026, released the provisional answer key for both Paper 1 and Paper 2 at 10:00 AM on Monday, May 25, 2026 at jeeadv.ac.in.\n\n• Provisional answer key release: May 25, 2026 at 10:00 AM IST\n• Papers covered: Paper 1 + Paper 2 (both compulsory)\n• Candidate response sheets: Released earlier on May 21, 2026\n• Objection window: May 25 (10:00 AM) — May 26, 2026 (5:00 PM IST)\n• Final answer key + result: June 1, 2026 at 10:00 AM IST\n• Architecture Aptitude Test (AAT) registration: Opens after the result\n\nApproximately 1.5 lakh engineering aspirants — the top JEE Main 2026 qualifiers — appeared in JEE Advanced 2026 on May 17, 2026. The answer key lets candidates cross-check their marked responses against the official answers and estimate probable scores ahead of the JoSAA 2026 IIT counselling.\n\nHow to raise an objection: Log in at jeeadv.ac.in using the JEE Advanced registration number and date of birth, open the Provisional Answer Key Challenge link, select the disputed question(s), upload supporting material and pay the per-question challenge fee. All challenges are reviewed by IIT Roorkee before the final key is published with the result on June 1.\n\nFor AP/TS aspirants: JoSAA 2026 counselling for IITs/NITs/IIITs/GFTIs typically begins within a week of the JEE Advanced result and runs 5–6 rounds in June–July. IIT Hyderabad continues to be the most popular IIT for Telugu-state candidates, followed by IIT Madras, Bombay and Roorkee.",
    category: "general",
    state: "Both",
    priority: "high",
    source: "JEE (Advanced) 2026 — IIT Roorkee Provisional Answer Key Notice",
    sourceUrl: "https://jeeadv.ac.in/",
    tags: ["JEE Advanced", "IIT Roorkee", "Answer Key", "Objections", "May 25", "2026"],
  },
  // ── New: May 20, 2026 ─────────────────────────────────────────
  {
    id: "neet-ug-2026-cancelled-re-exam-june-21",
    date: "2026-05-20",
    title: "NEET UG 2026 Cancelled Due to Paper Leak — Re-Exam Scheduled for June 21",
    summary: "NTA has cancelled the NEET UG 2026 exam held on May 3 after a confirmed question paper leak. A fresh re-exam (Re-NEET 2026) will be conducted on June 21, 2026 for all 22.79 lakh registered candidates. CBI is investigating.",
    body: "The National Testing Agency (NTA) has cancelled the NEET UG 2026 examination that was conducted on May 3, 2026 following confirmation of a question paper leak. The Central Bureau of Investigation (CBI) has taken over the probe.\n\nKey developments:\n• A PDF containing approximately 500–600 questions had circulated on Telegram from April 29, 2026 — days before the exam. Around 180 questions were reported to match the actual NEET UG 2026 paper.\n• CBI arrested multiple suspects including a biology lecturer who was part of the NTA paper-setting committee.\n• The CBI has indicated the leak can be traced to a source inside the NTA itself.\n\nRe-NEET 2026 schedule:\n• Re-exam date: June 21, 2026 (Saturday)\n• Timing: 2:00 PM – 5:15 PM (15 minutes extra compared to the original exam)\n• Mode: Pen-and-paper\n• City choice filling / correction window: Open until May 21, 2026 at neet.nta.nic.in\n• Admit card: Expected by June 14, 2026\n• Exam fee: Will be refunded to original bank accounts of payers for the cancelled May 3 exam\n• All 22,79,743 registered candidates are eligible to appear\n\nFor AP/TS aspirants: The NEET UG 2026 result timeline is now delayed. State counselling for MBBS/BDS at Dr. NTR UHS (AP) and KNRUHS (Telangana) will begin only after the Re-NEET result, now expected in July 2026 instead of June.\n\nEducation Minister Dharmendra Pradhan has announced that NEET UG will shift to Computer-Based Test (CBT) mode from 2027 onwards to prevent future paper leaks.",
    category: "general",
    state: "Both",
    priority: "high",
    source: "NTA / CBI — NEET UG 2026 Cancellation and Re-Exam Notice",
    sourceUrl: "https://neet.nta.nic.in/",
    tags: ["NEET UG", "Cancelled", "Paper Leak", "Re-Exam", "CBI", "NTA", "June 21", "2026"],
  },
  {
    id: "ts-ecet-2026-answer-key-released-may-20",
    date: "2026-05-20",
    title: "TS ECET 2026 — Answer Key Released, Objection Window Closes May 20 at 7 PM",
    summary: "Osmania University has released the TS ECET 2026 provisional answer key, response sheets and question papers at ecet.tgche.ac.in. Candidates can raise objections until May 20, 2026 at 7:00 PM. Result expected in June 2026.",
    body: "The provisional answer key, candidate response sheets and master question papers for TS (TG) ECET 2026 have been released by Osmania University at ecet.tgche.ac.in.\n\n• Exam conducted: May 15, 2026 (CBT mode)\n• Answer key released: May 2026\n• Last date to raise objections: May 20, 2026 at 7:00 PM\n• Objection submission: Via the official portal (login with registration number and DOB)\n• Result: Expected June 2026\n• Counselling: Typically July–August 2026\n\nCandidates should download their response sheets and cross-check with the provisional key before the objection deadline. The final answer key will be published along with the result after reviewing all objections.\n\nTS ECET is the lateral-entry test for diploma holders and B.Sc graduates seeking direct admission into the second year of B.Tech / B.Pharm programmes in Telangana.",
    category: "general",
    state: "TS",
    priority: "medium",
    source: "TGCHE / Osmania University — TS ECET 2026 Answer Key",
    sourceUrl: "https://ecet.tgche.ac.in/",
    tags: ["TS ECET", "TG ECET", "Answer Key", "Lateral Entry", "2026"],
  },
  // ── New: May 19, 2026 ─────────────────────────────────────────
  {
    id: "ap-eapcet-2026-engineering-exam-concluded-may-18",
    date: "2026-05-19",
    title: "AP EAPCET 2026 — Engineering Exam Concludes May 18; Preliminary Key Rescheduled to May 25",
    summary: "AP EAPCET 2026 Engineering was conducted across five days (May 12, 13, 14, 15 & 18). The preliminary answer key release was later rescheduled from May 23 to May 25, 2026 at 11 AM (see the May 25 update); objection window now closes May 27 at 11 AM. Final result: June 1, 2026.",
    body: "JNTU Kakinada has successfully concluded the AP EAPCET 2026 Engineering examination on May 18, 2026. The exam was held over five days (May 12, 13, 14, 15 and 18) in two daily shifts of three hours each.\n\nNext steps (revised — see May 25 update for the latest):\n• Preliminary answer key + individual response sheets: May 25, 2026 at 11:00 AM at cets.apsche.ap.gov.in (revised from the earlier May 23 indication; response sheets went live before that)\n• Objection window: Open until May 27, 2026 at 11:00 AM\n• Final result + rank card: June 1, 2026\n• Agriculture/Pharmacy (APECET) stream: May 19–20, 2026\n\nHow objections work: After downloading the preliminary key from the candidate login (hall ticket + DOB), students can challenge any question via the \"Key Objections\" link. Each objection must include the disputed question ID, a clear reason and supporting evidence (textbook scan, derivation, etc.) — APSCHE / JNTUK will review all objections before publishing the final key alongside the result.\n\nWhat to do now: Download and save your response sheet; cross-check with the preliminary key; raise objections only with citable evidence before the 11 AM, May 27 deadline. AP EAPCET counselling is expected to begin in the first week of July 2026, conducted by APSCHE in two regular rounds plus a spot round. Convener-quota fees for the 2025–28 block are governed by APHERMC; management-quota fees by individual colleges.",
    category: "eapcet",
    state: "AP",
    priority: "high",
    source: "APSCHE / JNTU Kakinada — AP EAPCET 2026 Schedule",
    sourceUrl: "https://cets.apsche.ap.gov.in/EAPCET/",
    tags: ["AP EAPCET", "Engineering", "Answer Key", "Result", "2026"],
  },
  // ── New: May 17, 2026 ─────────────────────────────────────────
  {
    id: "tg-eapcet-2026-results-declared-may-17",
    date: "2026-05-17",
    title: "TG EAPCET 2026 Results Declared — 77.25% Qualified; M Rushi (Medchal) Tops Engineering",
    summary: "TGCHE and JNTU Hyderabad declared TG EAPCET 2026 results on May 17 at 11 AM. Out of 2,82,195 candidates, 2,18,998 qualified (77.25%). Engineering topper: M Rushi (Medchal–Malkajgiri) with 156.63 marks. Agriculture & Pharmacy topper: Mukkaram Ahmed (Hyderabad) with 150.18 marks.",
    body: "The Telangana Council of Higher Education (TGCHE) and JNTU Hyderabad released the TG EAPCET 2026 results on Sunday, May 17, 2026 at 11:00 AM at Golden Jubilee Hall, JNTUH. The results were declared by Advisor (Public Affairs) K. Keshava Rao, Secretary (Education) Yogita Rana, TGCHE Chairman V. Balakista Reddy and other officials.\n\nOverall statistics:\n• Total candidates appeared: 2,82,195\n• Total candidates qualified: 2,18,998\n• Overall pass percentage: 77.25%\n\nStream-wise:\n• Engineering — 1,97,242 appeared, 1,44,704 qualified (73.36%)\n• Agriculture & Pharmacy — 84,954 appeared, 73,294 qualified (86.27%)\n\nTop rankers:\n• Engineering AIR 1: M. Rushi — 156.6353 marks (Medchal–Malkajgiri, Telangana)\n• Engineering AIR 2: Bejugama Anshul — 148.7082 marks (Medchal, Telangana)\n• Agriculture & Pharmacy AIR 1: Mukkaram Ahmed — 150.1771 marks (Hyderabad)\n\nHow to download: Candidates can log in at eapcet.tgche.ac.in using registration number, hall ticket number and date of birth. The rank card lists subject-wise marks, normalised score, percentile and overall rank.\n\nWhat's next: TG EAPCET 2026 counselling is expected to begin in late June – early July 2026 with three regular rounds plus a special round. Convenor-quota tuition fees for 2025–26 to 2027–28 are now locked under G.O. Ms. No. 06 (₹45,000 floor, ₹1,83,000 ceiling at CBIT). Candidates should prepare originals: SSC, Inter memos, TC, study certificates, caste certificate (if applicable), income certificate, EWS certificate (if applicable) and Aadhaar.",
    category: "eapcet",
    state: "TS",
    priority: "high",
    source: "TGCHE / JNTU Hyderabad — TG EAPCET 2026 Result Notification",
    sourceUrl: "https://eapcet.tgche.ac.in/",
    tags: ["TG EAPCET", "TS EAMCET", "Results", "Toppers", "M Rushi", "2026"],
  },
  {
    id: "jee-advanced-2026-exam-concluded-may-17",
    date: "2026-05-17",
    title: "JEE Advanced 2026 Conducted by IIT Roorkee on May 17 — Result on June 1",
    summary: "IIT Roorkee successfully conducted JEE Advanced 2026 on May 17 in two papers. Question papers and response sheets are now public at jeeadv.ac.in. Provisional answer key was released on May 25 (see May 25 update); final result: June 1, 2026.",
    body: "JEE Advanced 2026, the gateway to all 23 IITs, was conducted on Sunday, May 17, 2026 by IIT Roorkee (the zonal coordinator for 2026). Both papers were held in CBT mode.\n\n• Paper 1: 09:00–12:00 (48 questions reported)\n• Paper 2: 14:30–17:30 (54 questions reported)\n• Both papers compulsory\n\nPost-exam milestones:\n• Question papers: Released on the day of the exam at jeeadv.ac.in\n• Candidate response sheets: Released May 21, 2026\n• Provisional answer key: Released May 25, 2026 at 10:00 AM (see the May 25 update for objection details)\n• Objection window: Through May 26, 2026 at 5:00 PM\n• Final answer key: Along with result\n• Result: June 1, 2026 at 10:00 AM\n• Architecture Aptitude Test (AAT) registration: Opens after JEE Advanced result\n\nInformal student feedback (subject to verification with the official key): Physics was reported to be the toughest section in Paper 1, while Mathematics felt the most challenging in Paper 2. The cutoff for IIT counselling (JoSAA 2026) will be confirmed with the result.\n\nFor AP/TS aspirants: IIT Hyderabad continues to be the most popular IIT for Telugu-state candidates, followed by IIT Madras, Bombay and Roorkee. JoSAA counselling typically begins within a week of the JEE Advanced result and runs 5–6 rounds in June–July.",
    category: "general",
    state: "Both",
    priority: "high",
    source: "JEE (Advanced) 2026 — IIT Roorkee",
    sourceUrl: "https://jeeadv.ac.in/",
    tags: ["JEE Advanced", "IIT Roorkee", "IIT", "Result", "2026"],
  },
  // ── New: May 16, 2026 ─────────────────────────────────────────
  {
    id: "ap-icet-2026-results-may-16",
    date: "2026-05-16",
    title: "AP ICET 2026 Results Declared — 91.41% Qualified; Rank Cards Out",
    summary: "APSCHE declared AP ICET 2026 results on May 16 at cets.apsche.ap.gov.in. Of 23,198 candidates who appeared, 21,205 qualified — a pass percentage of 91.41%. MBA/MCA counselling expected in June–July.",
    body: "The Andhra Pradesh State Council of Higher Education (APSCHE) released the AP ICET 2026 results on May 16, 2026.\n\n• Total candidates appeared: 23,198\n• Total candidates qualified: 21,205\n• Pass percentage: 91.41%\n• Exam conducted on: May 2, 2026\n• Rank card download: cets.apsche.ap.gov.in/ICET (login with hall ticket + DOB)\n\nAP ICET is conducted by APSCHE for admission into MBA and MCA programmes across Andhra Pradesh universities and affiliated colleges (Andhra University, SVU, ANU, KU, JNTU-K, JNTU-A and their constituent/affiliated colleges).\n\nNext steps:\n• Download and save the rank card and scorecard\n• Watch for the AP ICET 2026 counselling notification (expected June–July 2026)\n• Keep originals ready: degree certificate, marks memos, transfer certificate, caste/income/EWS certificates as applicable, Aadhaar\n\nCategory-wise qualifying marks: General/BC must secure at least 25% (50 out of 200). SC/ST candidates are eligible for ranking based on any score.",
    category: "general",
    state: "AP",
    priority: "medium",
    source: "APSCHE — AP ICET 2026 Result Notification",
    sourceUrl: "https://cets.apsche.ap.gov.in/ICET/",
    tags: ["AP ICET", "MBA", "MCA", "Results", "2026"],
  },
  // ── New: May 15, 2026 ─────────────────────────────────────────
  {
    id: "tg-ecet-2026-exam-conducted-may-15",
    date: "2026-05-15",
    title: "TS ECET 2026 Conducted on May 15 — Answer Key Now Released (See May 20 Update)",
    summary: "Osmania University conducted TS (TG) ECET 2026 on May 15, 2026 in CBT mode. The provisional answer key, response sheets and question papers have been released. Objection window closes May 20 at 7 PM. Result expected June 2026.",
    body: "Osmania University, on behalf of the Telangana Council of Higher Education (TGCHE), successfully conducted TS (TG) ECET 2026 — the lateral-entry test for diploma holders and B.Sc graduates seeking direct admission into the second year of B.Tech / B.Pharm programmes in Telangana — on May 15, 2026 in CBT mode.\n\n• Eligibility streams: Diploma in Engineering / B.Sc Mathematics graduates for lateral B.Tech; Diploma in Pharmacy for lateral B.Pharm\n• Official portal: ecet.tgche.ac.in\n• Provisional answer key + response sheet: Expected within 7–10 days\n• Result: Expected late May / early June 2026\n• Counselling: Typically July–August 2026 (after main TG EAPCET counselling concludes)\n\nCandidates should keep their diploma/B.Sc marks memos, SSC certificate, study/conduct certificate, caste certificate (if applicable) and Aadhaar ready for the counselling document-verification stage. Lateral-entry seats are filled in the 10% supernumerary quota over and above the sanctioned intake of each engineering branch.",
    category: "general",
    state: "TS",
    priority: "medium",
    source: "TGCHE / Osmania University — TS ECET 2026",
    sourceUrl: "https://ecet.tgche.ac.in/",
    tags: ["TS ECET", "TG ECET", "Lateral Entry", "2026"],
  },
  // ── New: May 14, 2026 ─────────────────────────────────────────
  {
    id: "ap-pgecet-2026-results-may-14",
    date: "2026-05-14",
    title: "AP PGECET 2026 Results Released — Rank Cards Available",
    summary: "Andhra University, on behalf of APSCHE, declared AP PGECET 2026 results on May 14. Candidates can download rank cards at cets.apsche.ap.gov.in. Counselling expected with AP EAPCET counselling in July–August.",
    body: "Andhra University (Visakhapatnam), conducting body for AP PGECET on behalf of APSCHE, released the AP PGECET 2026 results on May 14, 2026.\n\n• Exam dates: April 28, 29 & 30, 2026 (CBT, two daily sessions)\n• For admissions to: M.E/M.Tech, M.Pharm, M.Arch, Pharm.D (PB)\n• Rank card download: cets.apsche.ap.gov.in/PGECET (registration number + AP PGECET hall ticket + DOB)\n\nQualifying criteria:\n• General/BC: 25% (30 out of 120) minimum\n• SC/ST: No minimum — eligible for ranking based on any score\n\nThe rank card shows marks secured, qualifying status, AP PGECET rank and percentile. AP PGECET 2026 counselling is expected to run alongside AP EAPCET counselling in July–August 2026. Candidates holding both a valid GATE score and AP PGECET qualification have an edge — GATE-qualified seats are filled first in M.Tech counselling, with PGECET ranks filling the remaining seats.",
    category: "general",
    state: "AP",
    priority: "low",
    source: "APSCHE / Andhra University — AP PGECET 2026 Result",
    sourceUrl: "https://cets.apsche.ap.gov.in/PGECET/",
    tags: ["AP PGECET", "M.Tech", "M.Pharm", "Results", "2026"],
  },
  // ── New: May 6, 2026 ──────────────────────────────────────────
  {
    id: "neet-ug-2026-answer-key-may-6",
    date: "2026-05-06",
    title: "NEET UG 2026 — Provisional Answer Key Was Released May 6 (Exam Now Cancelled)",
    summary: "NTA had released the NEET UG 2026 provisional answer key on May 6 at neet.nta.nic.in for codes 11, 12, 13 and 14. However, the May 3 exam has since been cancelled due to a confirmed paper leak. A re-exam (Re-NEET) is scheduled for June 21, 2026. See the May 20 update.",
    body: "The National Testing Agency (NTA) released the NEET UG 2026 provisional answer key, response sheets and question papers on Wednesday, May 6, 2026 at neet.nta.nic.in — three days after the May 3 exam.\n\n• Answer key codes released: 11, 12, 13 and 14\n• Download portal: neet.nta.nic.in (login with application number + password / DOB)\n• Objection / challenge window: Per NTA notification on the portal (fee per challenge as applicable)\n• Final answer key and result: Expected 2nd or 3rd week of June 2026\n\nExam-day snapshot (May 3, 2026):\n• Candidates registered: 22,79,743\n• Approximate attendance: 97% (~22.11 lakh appeared)\n• Centres: 551 cities in India + 14 international locations\n• Mode: Pen-and-paper, 2:00 PM – 5:00 PM\n\nReported difficulty (informal student/coaching feedback — to be verified against the final key): Overall moderate, slightly easier than NEET 2025. Physics was the toughest section; Chemistry was balanced and manageable; Biology was the most scoring overall, though Botany felt lengthy.\n\nAP/TS aspirants: NEET UG 2026 scores are required for all MBBS/BDS admissions in Andhra Pradesh (Dr. NTR UHS counselling) and Telangana (KNRUHS counselling), plus the central 15% AIQ pool (MCC) and deemed universities. AP/TS state counselling typically begins in July, after the NEET UG result.",
    category: "general",
    state: "Both",
    priority: "high",
    source: "NTA — NEET UG 2026 Provisional Answer Key Notice",
    sourceUrl: "https://neet.nta.nic.in/",
    tags: ["NEET UG", "Answer Key", "NTA", "Result", "2026"],
  },
  // ── New: May 3, 2026 ──────────────────────────────────────────
  {
    id: "neet-ug-2026-exam-conducted-may-3",
    date: "2026-05-03",
    title: "NEET UG 2026 Was Conducted on May 3 — Now Cancelled Due to Paper Leak",
    summary: "NTA conducted NEET UG 2026 on May 3 across 551 Indian cities. About 22.11 lakh candidates appeared. However, the exam has since been cancelled due to a confirmed question paper leak. A re-exam (Re-NEET) is scheduled for June 21, 2026. See the May 20 update.",
    body: "The National Testing Agency (NTA) successfully conducted NEET UG 2026, the single medical entrance exam for MBBS, BDS, BAMS, BHMS, BVSc and allied AYUSH courses, on Sunday, May 3, 2026.\n\n• Timing: 2:00 PM – 5:00 PM (pen-and-paper mode)\n• Cities: 551 in India + 14 international locations\n• Candidates registered: 22,79,743\n• Approximate attendance: 97% (~22.11 lakh appeared)\n\nAdmit cards were released on April 27 at 10 AM (a one-day postponement from the original April 26 schedule). The exam-city intimation slip had already been issued on April 12.\n\nWhat's next:\n• Provisional answer key, response sheets and question papers: Released May 6, 2026 at neet.nta.nic.in (see May 6 update)\n• Objection window: Per NTA notification\n• Final result: Expected 2nd–3rd week of June 2026\n\nFor AP/TS students: NEET UG 2026 scores are the sole criterion for MBBS/BDS admissions in Andhra Pradesh (Dr. NTR UHS counselling) and Telangana (KNRUHS counselling), as well as the all-India 15% quota (MCC) and deemed universities. State counselling notifications typically open within 1–2 weeks of the NEET UG result.",
    category: "general",
    state: "Both",
    priority: "high",
    source: "NTA — NEET UG 2026 Exam",
    sourceUrl: "https://neet.nta.nic.in/",
    tags: ["NEET UG", "NTA", "Medical", "MBBS", "2026"],
  },
  // ── New: April 26, 2026 ───────────────────────────────────────
  {
    id: "neet-ug-2026-admit-card-postponed-april-27",
    date: "2026-04-26",
    title: "NEET UG 2026 — Admit Card Was Released April 27 (May 3 Exam Now Cancelled)",
    summary: "NTA released NEET UG 2026 admit cards on April 27 at neet.nta.nic.in. The May 3 exam was conducted but has since been cancelled due to a paper leak. A re-exam is scheduled for June 21, 2026. New admit cards will be issued.",
    body: "The National Testing Agency (NTA) has postponed the release of NEET UG 2026 admit cards by one day. Originally scheduled for April 26, the hall tickets will now be available from 10:00 AM on Monday, April 27, 2026 at neet.nta.nic.in.\n\nKey points:\n• New admit card release: April 27, 2026, 10:00 AM IST\n• Download portal: neet.nta.nic.in (login with application number + password/DOB)\n• Exam date: May 3, 2026 (Sunday) — UNCHANGED\n• Timing: 2:00 PM – 5:00 PM (pen-and-paper mode)\n• Exam city intimation slip was released April 12, 2026 (separate from admit card)\n\nNTA's official announcement (via its X handle): \"NEET Admit Cards will be available to all candidates by 10 AM on Monday, 27th April 2026. Use the last Sunday before the exam for a practice test or revising concepts. Stay Calm. Keep yourself hydrated.\"\n\nWhat to do today (April 26): Use the day for revision or a full mock test. Do not download admit cards from any unofficial source. The only authoritative portal is neet.nta.nic.in.\n\nWhat to carry on exam day: Printed admit card + one valid photo ID (Aadhaar preferred). Reach the centre at least 1.5 hours before the exam — gates close 30 minutes before start. AP/TS aspirants will use NEET UG 2026 scores for MBBS/BDS counselling at Dr. NTR UHS (AP) and KNRUHS (Telangana), as well as MCC central quota and deemed universities.",
    category: "general",
    state: "Both",
    priority: "high",
    source: "NTA (NEET UG 2026 Admit Card Notice, 26.04.2026)",
    sourceUrl: "https://neet.nta.nic.in/",
    tags: ["NEET UG", "Admit Card", "Postponed", "NTA", "May 3", "2026"],
  },
  // ── New: April 21, 2026 ───────────────────────────────────────
  {
    id: "ts-ecet-2026-deadline-extended-april-23",
    date: "2026-04-21",
    title: "TS ECET 2026 — Registration Deadline Extended to April 23 (Without Late Fee)",
    summary: "Osmania University has extended the TS ECET 2026 registration deadline. Candidates can apply without late fee until April 23, 2026. Late-fee window remains open until May 12. Exam: May 15, 2026.",
    body: "Supersedes the earlier April 18 deadline: the TS (TG) ECET 2026 regular registration window has been extended to April 23, 2026.\n\n• Last date without late fee: April 23, 2026\n• Late fee applications accepted: until May 12, 2026\n• Exam date: May 15, 2026\n• Application fee: ₹900 (General), ₹500 (SC/ST/PwD)\n• Official portal: ecet.tgche.ac.in\n• Conducting body: Osmania University on behalf of TGCHE\n\nTS ECET is the lateral-entry test for diploma holders and B.Sc graduates seeking direct admission into the second year of B.Tech / B.Pharm programmes in Telangana. Payment options include debit card, credit card, and net banking. Candidates should finalise their application before April 23 to avoid late fees; documents (SSC, diploma/B.Sc marks memos, caste certificate, Aadhaar) must match the application exactly for counselling verification (expected July–August 2026).",
    category: "general",
    state: "TS",
    priority: "medium",
    source: "TGCHE / Osmania University — TS ECET 2026 Notification",
    sourceUrl: "https://ecet.tgche.ac.in/",
    tags: ["TS ECET", "TG ECET", "Lateral Entry", "Deadline Extended", "2026"],
  },
  {
    id: "jee-main-2026-session-2-results-out-april-20",
    date: "2026-04-21",
    title: "JEE Main 2026 Session 2 Results Declared — 5 Toppers from AP & Telangana, AIR 2 Jonnala Roshan (AP)",
    summary: "NTA declared JEE Main 2026 Session 2 results on April 20. 26 students scored a perfect 100 percentile — 5 are from Andhra Pradesh and Telangana. Top 2,50,182 qualify for JEE Advanced.",
    body: "The National Testing Agency (NTA) released JEE Main 2026 Session 2 results and final answer key on April 20, 2026 at jeemain.nta.nic.in.\n\nKey highlights:\n• 26 candidates scored a perfect 100 NTA percentile in Paper 1 (B.E./B.Tech)\n• Telugu states (AP + Telangana) contributed 5 of the 26 100-percentilers — the joint-highest tally\n• AIR 1: Aarush Singhal (Chandigarh)\n• AIR 2: Jonnala Roshan Mandeep Reddy (Andhra Pradesh)\n• AIR 3: Shreyas Mishra (Delhi)\n• Top female performer (All India): Mallavarapu Aasna (Telangana) with 99.9982287 percentile — no female candidate hit 100 percentile this year\n• 12 of the Session 2 toppers had also topped Session 1\n\nJEE Advanced eligibility:\n• The top 2,50,182 candidates — based on best of Session 1 + Session 2 scores — are eligible for JEE Advanced 2026\n• JEE Advanced registration opens April 23 and closes May 2, 2026\n• JEE Advanced exam: May 17, 2026 (organised by IIT Roorkee)\n\nCandidates should download their scorecards from jeemain.nta.nic.in and retain them for counselling at JoSAA/CSAB as well as for AP/TS private-university admissions (GITAM, KL University, SRM AP, VIT-AP and Vignan's accept JEE Main scores).",
    category: "general",
    state: "Both",
    priority: "high",
    source: "NTA (JEE Main 2026 Session 2 Result Notification, 20.04.2026)",
    sourceUrl: "https://jeemain.nta.nic.in/",
    tags: ["JEE Main", "Session 2", "Results", "NTA", "Toppers", "2026"],
  },
  {
    id: "tg-engineering-fee-2025-28-go-ms-06",
    date: "2026-04-21",
    title: "Telangana Fixes 2025–28 B.Tech Fee Block — ₹45,000 Floor, ₹1.83 Lakh Cap (CBIT)",
    summary: "G.O. Ms. No. 06 dated 04.03.2026 fixes B.E./B.Tech tuition fees for 160 private unaided engineering colleges in Telangana for the 2025–26 to 2027–28 block. Minimum ₹45,000/yr; CBIT tops the list at ₹1,83,000/yr.",
    body: "The Telangana Higher Education (Technical Education) Department issued G.O. Ms. No. 06 on March 4, 2026 finalising the tuition fee structure for B.E./B.Tech programmes in private unaided engineering colleges for the three-year block 2025–26 to 2027–28. The order follows recommendations of the Telangana Admission and Fee Regulatory Committee (TAFRC).\n\nFee range:\n• Minimum annual tuition fee: ₹45,000\n• Maximum annual tuition fee: ₹1,83,000 (Chaitanya Bharathi Institute of Technology — CBIT, Hyderabad)\n• 160 private unaided engineering colleges covered\n• 63 colleges saw a fee hike relative to the 2022–25 block; some institutions saw reductions\n\nScope:\n• The fee fixed is the annual tuition fee only — it does NOT include special fee or admission fee\n• Institutions must collect fees for the applicable academic year (lump sum or in instalments)\n• Applies to both convenor quota (TGCHE counselling) and management quota seats, subject to category-wise rules\n\nWhat this means for students:\n• Convenor quota fees payable during TGCHE counselling (expected July–August 2026) are now locked for the three-year block\n• The government fee-reimbursement scheme will cover the convenor-quota tuition fee for eligible candidates as per current policy\n• Management-quota and NRI fees remain college-specific but are capped by the block ceiling\n\nTeluguColleges will update the per-college fee pages (/colleges/[slug]/fees) to reflect the 2025–28 block figures over the coming weeks as the TAFRC list is tabulated.",
    category: "fees",
    state: "TS",
    priority: "high",
    source: "Government of Telangana — Higher Education (TE) Dept., G.O. Ms. No. 06 dated 04.03.2026 / TAFRC",
    sourceUrl: "https://tafrc.telangana.gov.in/",
    tags: ["Telangana", "Engineering Fees", "TAFRC", "B.Tech", "2025-28", "CBIT", "Fee Block"],
  },
  {
    id: "neet-ug-2026-exam-may-3-admit-card-expected",
    date: "2026-04-21",
    title: "NEET UG 2026 — Original Schedule (May 3 Exam Now Cancelled; Re-Exam June 21)",
    summary: "NEET UG 2026 was originally scheduled for May 3. The exam was conducted but has since been cancelled due to a confirmed paper leak. Re-NEET 2026 is now scheduled for June 21, 2026. See the May 20 update for full details.",
    body: "The National Testing Agency (NTA) has confirmed key details for NEET UG 2026, the single medical/dental/AYUSH entrance exam for MBBS, BDS, BAMS, BHMS, B.V.Sc and allied courses.\n\n• Exam date: May 3, 2026 (Sunday)\n• Timing: 2:00 PM – 5:00 PM (pen-and-paper mode)\n• Exam city intimation slip: Released April 12, 2026\n• Admit card: Originally expected April 26, 2026 — postponed to April 27, 2026 at 10:00 AM (see April 26 update)\n• Download portal: neet.nta.nic.in\n\nWhat AP/TS aspirants should do now:\n• Check the city intimation slip on neet.nta.nic.in and plan travel/accommodation early\n• Carry the printed admit card + one valid photo ID (Aadhaar preferred) to the exam centre\n• Reach the centre at least 1.5 hours before the exam; centres close gate 30 minutes before start\n• NEET UG 2026 scores are required for all MBBS/BDS admissions in AP (Dr. NTR UHS counselling) and Telangana (KNRUHS counselling), as well as central quota (MCC) and deemed universities\n\nAP/TS medical counselling is expected to start after NEET UG results, typically in July 2026.",
    category: "general",
    state: "Both",
    priority: "high",
    source: "NTA (NEET UG 2026 Schedule)",
    sourceUrl: "https://neet.nta.nic.in/",
    tags: ["NEET UG", "Medical", "MBBS", "NTA", "Admit Card", "2026"],
  },
  {
    id: "jee-advanced-2026-registration-update-april-21",
    date: "2026-04-21",
    title: "Correction — JEE Advanced 2026 Organised by IIT Roorkee (Not IIT Dhanbad), Result June 1",
    summary: "Clarifying earlier reports: JEE Advanced 2026 is organised by IIT Roorkee. Registration runs April 23 – May 2; admit card May 11; exam May 17; result June 1, 2026.",
    body: "Confirmed schedule from the official JEE Advanced 2026 notification (jeeadv.ac.in):\n\n• Organising institute: IIT Roorkee (rotating zonal coordinator for 2026)\n• Registration opens (Indian nationals): April 23, 2026 at 10:00 IST\n• Registration closes: May 2, 2026 at 23:59 IST\n• Last date for fee payment: May 4, 2026\n• Admit card download: May 11–17, 2026\n• Exam: May 17, 2026 — Paper 1 (09:00–12:00), Paper 2 (14:30–17:30)\n• Result: June 1, 2026\n• Foreign/OCI/PIO registration opens: April 6, 2026\n\nEligibility: top 2,50,182 candidates from JEE Main 2026 (combined Session 1 + Session 2 best scores), subject to category and age rules. Architecture Aptitude Test (AAT) registration opens after the JEE Advanced result.\n\nThis notice corrects earlier coverage that referenced IIT Dhanbad and a June 8 result date — the authoritative source is the JEE (Advanced) 2026 portal.",
    category: "general",
    state: "Both",
    priority: "medium",
    source: "JEE (Advanced) 2026 — IIT Roorkee",
    sourceUrl: "https://jeeadv.ac.in/",
    tags: ["JEE Advanced", "IIT Roorkee", "Registration", "Correction", "2026"],
  },
  // ── New: April 12, 2026 ───────────────────────────────────────
  {
    id: "jee-main-2026-session-2-results-expected",
    date: "2026-04-12",
    title: "JEE Main 2026 Session 2 — Results Expected by April 20",
    summary: "JEE Main 2026 Session 2 exam concluded on April 9. Answer key released April 11. Final results and All India Ranks expected by April 20.",
    body: "JEE Main 2026 Session 2 has been completed successfully.\n\n• Exam conducted: April 2–9, 2026 (CBT mode)\n• Provisional answer key: Released April 11 at jeemain.nta.nic.in\n• Challenge window: Open until April 13, 2026\n• Final result & AIR: Expected by April 20, 2026\n\nSession 2 results will include JEE Advanced 2026 qualification cutoffs and final All India Ranks. Candidates who appeared in both sessions will be awarded the better of the two NTA scores.\n\nJEE Advanced 2026 registration opens April 23 (exam May 17). Top 2.5 lakh JEE Main qualifiers are eligible.\n\nFor AP/TS students — JEE Main scores are accepted by GITAM, KL University, SRM AP, and Vignan's for direct admission without separate entrance exams.",
    category: "general",
    state: "Both",
    priority: "high",
    source: "NTA",
    sourceUrl: "https://jeemain.nta.nic.in/",
    tags: ["JEE Main", "Session 2", "Results", "NTA", "JEE Advanced", "2026"],
  },
  {
    id: "jee-advanced-2026-registration-april-23",
    date: "2026-04-12",
    title: "JEE Advanced 2026 — Registration Opens April 23, Exam on May 17",
    summary: "JEE Advanced 2026 registration opens April 23 and closes May 2. Exam scheduled for May 17, organised by IIT Roorkee. Top 2.5 lakh JEE Main qualifiers eligible.",
    body: "JEE Advanced 2026, the gateway to all 23 IITs, has confirmed its schedule.\n\n• Registration opens: April 23, 2026 (10:00 IST)\n• Registration closes: May 2, 2026 (23:59 IST)\n• Last date for fee payment: May 4, 2026\n• Admit card download: May 11, 2026\n• Exam date: May 17, 2026 (Paper 1: 9 AM–12 PM, Paper 2: 2:30 PM–5:30 PM)\n• Organising institute: IIT Roorkee\n• Result: June 1, 2026\n\nEligibility: Top 2,50,000 candidates from JEE Main 2026 (across all categories). Candidates must have been born on or after October 1, 2001 (relaxation for reserved categories).\n\nIIT Hyderabad remains a top choice for AP/TS students. Architecture Aptitude Test (AAT) registration opens after JEE Advanced results.",
    category: "general",
    state: "Both",
    priority: "high",
    source: "JEE Advanced 2026",
    sourceUrl: "https://jeeadv.ac.in/",
    tags: ["JEE Advanced", "IIT", "Registration", "2026"],
  },
  {
    id: "tg-eapcet-2026-admit-cards-april",
    date: "2026-04-12",
    title: "TG EAPCET 2026 — Admit Cards: Agriculture April 23, Engineering April 27",
    summary: "TG EAPCET 2026 admit cards will be released on April 23 (Agriculture/Pharmacy) and April 27 (Engineering). Correction window has closed.",
    body: "TG EAPCET 2026 admit card schedule has been confirmed.\n\n• Agriculture/Pharmacy admit card: April 23, 2026\n• Engineering admit card: April 27, 2026\n• Download at: eapcet.tgche.ac.in\n• Application correction window: Closed (ended April 8)\n\nExam schedule:\n• Agriculture/Pharmacy: May 4–5, 2026\n• Engineering: May 9–11, 2026\n• Shifts: Morning (9 AM–12 PM) and Afternoon (3 PM–6 PM)\n• 160 MCQs for 160 marks, no negative marking\n\nLate registration is still open with progressive late fees (₹1,000 until April 25, ₹2,000 until April 28, ₹10,000 until May 2). Download admit cards using your registration number and date of birth.",
    category: "eapcet",
    state: "TS",
    priority: "high",
    source: "TGCHE / JNTU Hyderabad",
    sourceUrl: "https://eapcet.tgche.ac.in/",
    tags: ["TG EAPCET", "Admit Card", "2026"],
  },
  {
    id: "ts-ecet-2026-last-date-april-18",
    date: "2026-04-12",
    title: "TS ECET 2026 — Earlier Deadline Was April 18 (Superseded)",
    summary: "As originally notified, TS ECET 2026 had a regular registration deadline of April 18. This window was later extended — see the April 21 update.",
    body: "This item is retained as a historical reference. As originally notified in early April:\n\n• Regular deadline (no late fee): April 18, 2026\n• Exam date: May 15, 2026\n• Eligibility: Diploma holders and B.Sc graduates seeking lateral entry into B.Tech/B.Pharm second year\n• Official website: ecet.tgche.ac.in\n\nUpdate (April 21, 2026): Osmania University — which is conducting TS ECET 2026 on behalf of TGCHE — extended the registration deadline to April 23, 2026 without late fee. A subsequent late-fee window remains open until May 12, 2026. See the April 21 news item for the current timeline.\n\nCandidates should verify all timelines on the official portal before applying.",
    category: "general",
    state: "TS",
    priority: "low",
    source: "TGCHE / Osmania University",
    sourceUrl: "https://ecet.tgche.ac.in/",
    tags: ["TS ECET", "Lateral Entry", "2026", "Diploma", "Superseded"],
  },
  {
    id: "ap-icet-2026-admit-card-released",
    date: "2026-04-12",
    title: "AP ICET 2026 — Admit Card Released, Exam on May 2",
    summary: "AP ICET 2026 admit cards are now available for download. The MBA/MCA entrance exam is scheduled for May 2, 2026.",
    body: "AP ICET 2026 admit cards have been released for download.\n\n• Admit card available at: cets.apsche.ap.gov.in/ICET\n• Exam date: May 2, 2026\n• Download using: Registration number + date of birth\n• Late fee registration: Closed (final deadline was April 5)\n\nAP ICET is the entrance test for MBA and MCA admissions in all AP-affiliated universities and colleges. Candidates should download and print their admit cards well in advance.\n\nEnsure you carry a valid photo ID along with the admit card to the exam centre. Check the venue details on your admit card and plan your travel accordingly.",
    category: "general",
    state: "AP",
    priority: "medium",
    source: "APSCHE",
    sourceUrl: "https://cets.apsche.ap.gov.in/ICET/",
    tags: ["AP ICET", "MBA", "MCA", "Admit Card", "2026"],
  },
  {
    id: "ap-pgecet-2026-exam-april-28-30",
    date: "2026-04-12",
    title: "AP PGECET 2026 — Exam on April 28–30, Admit Cards Released April 15",
    summary: "AP PGECET 2026 exam is scheduled for April 28–30, 2026 in two daily sessions. Admit cards were released on April 15, 2026 at cets.apsche.ap.gov.in for M.Tech, M.Pharm, M.Arch and Pharm.D (PB) aspirants.",
    body: "AP Post Graduate Engineering Common Entrance Test (AP PGECET) 2026 is just days away.\n\n• Exam dates: April 28, 29 & 30, 2026 (CBT, two sessions/day)\n• For admissions to: M.E/M.Tech, M.Pharm, M.Arch, Pharm.D (PB)\n• Conducting university: Andhra University, Visakhapatnam (on behalf of APSCHE)\n• Admit card: Released April 15, 2026 — download at cets.apsche.ap.gov.in using registration number, qualifying-exam hall ticket number and date of birth\n• Result: May 14, 2026 (expected)\n\nThis exam is for B.Tech/B.E. graduates seeking postgraduate engineering education in Andhra Pradesh. Qualifying AP PGECET along with a valid GATE score improves chances during counselling.\n\nCounselling is expected in July–August 2026 along with AP EAPCET counselling. Carry a printed admit card and a valid photo ID (Aadhaar preferred) to the exam centre.",
    category: "general",
    state: "AP",
    priority: "low",
    source: "APSCHE",
    sourceUrl: "https://cets.apsche.ap.gov.in/",
    tags: ["AP PGECET", "M.Tech", "M.Pharm", "2026"],
  },
  // ── Updated: March 26, 2026 ────────────────────────────────────
  {
    id: "ap-eapcet-2026-correction-window-open",
    date: "2026-03-26",
    title: "AP EAPCET 2026 — Application Correction Window Closed, Admit Cards April 28",
    summary: "The AP EAPCET 2026 correction window (March 26–28) has closed. Next milestone: admit card download from April 28.",
    body: "The AP EAPCET 2026 application form correction window has closed.\n\n• Correction window: March 26–28, 2026 (closed)\n• Status: All corrections finalized\n\nUpcoming key dates:\n• Admit card download: April 28, 2026 onwards at cets.apsche.ap.gov.in\n• Engineering exam: May 12, 13, 14, 15 & 18, 2026\n• Agriculture/Pharmacy exam: May 19 & 20, 2026\n• Result: June 1, 2026\n\nCandidates should now focus on exam preparation. Admit cards will be downloadable using registration number or payment reference ID, qualifying exam hall ticket number, and date of birth.",
    category: "eapcet",
    state: "AP",
    priority: "high",
    source: "APSCHE",
    sourceUrl: "https://cets.apsche.ap.gov.in/EAPCET/",
    tags: ["AP EAPCET", "Correction Window", "Admit Card", "2026"],
  },
  {
    id: "tg-eapcet-2026-registration-deadline-april-4",
    date: "2026-03-26",
    title: "TG EAPCET 2026 — Registration Closed, Late Fee Window Still Open",
    summary: "TG EAPCET 2026 regular registration (April 4) has closed. Late fee applications still accepted until May 2. Correction window ended April 8.",
    body: "TG EAPCET (formerly TS EAMCET) 2026 registration update.\n\n• Regular deadline (April 4): Closed\n• Form correction window (April 6–8): Closed\n• Late fee registration: Still open (₹1,000 until April 25, ₹2,000 until April 28, ₹10,000 until May 2)\n• Official website: eapcet.tgche.ac.in\n\nExam schedule:\n• Agriculture/Pharmacy: May 4–5, 2026\n• Engineering: May 9–11, 2026\n• Admit cards: Agriculture April 23 | Engineering April 27\n\nThe exam will have 160 MCQs for 160 marks with no negative marking. Two shifts per day — 9 AM to 12 PM and 3 PM to 6 PM.",
    category: "eapcet",
    state: "TS",
    priority: "high",
    source: "TGCHE / JNTU Hyderabad",
    sourceUrl: "https://eapcet.tgche.ac.in/",
    tags: ["TG EAPCET", "TS EAMCET", "Registration", "Late Fee", "2026"],
  },
  {
    id: "jee-main-2026-session-2-april",
    date: "2026-03-26",
    title: "JEE Main 2026 Session 2 — Exam Completed, Results Expected April 20",
    summary: "JEE Main 2026 Session 2 was conducted April 2–9. Answer key released April 11. Results and AIR expected by April 20.",
    body: "JEE Main 2026 Session 2 has been completed.\n\n• Exam conducted: April 2–9, 2026 (CBT mode)\n• Answer key: Released April 11 at jeemain.nta.nic.in\n• Result: Expected by April 20, 2026\n\nSession 2 results will include JEE Advanced 2026 qualification cutoffs and All India Ranks. Candidates who appeared in both sessions will be awarded the better of the two NTA scores.\n\nJEE Advanced 2026: Registration opens April 23, exam on May 17.\n\nFor students targeting AP/TS private and deemed universities — JEE Main scores are accepted by GITAM (GAT waiver), KL University, SRM AP, and Vignan's (V-SAT waiver) for direct admission.",
    category: "general",
    state: "Both",
    priority: "high",
    source: "NTA",
    sourceUrl: "https://jeemain.nta.nic.in/",
    tags: ["JEE Main", "Session 2", "NTA", "Results", "2026"],
  },
  {
    id: "ap-icet-2026-late-fee-deadline-march-26",
    date: "2026-03-26",
    title: "AP ICET 2026 — Registration Closed, Admit Card Now Available",
    summary: "AP ICET 2026 registration has closed (final deadline April 5). Admit cards are now available for download. Exam on May 2.",
    body: "AP ICET 2026 (for MBA/MCA admissions) registration is now closed.\n\n• Regular deadline: Closed (March 23)\n• Final late fee deadline (₹10,000): Closed (April 5)\n• Admit card: Now available at cets.apsche.ap.gov.in/ICET\n• Exam date: May 2, 2026\n\nCandidates who registered should download their admit cards immediately. Carry a valid photo ID along with the printed admit card to the exam centre.\n\nAP ICET is conducted by APSCHE for admission to MBA and MCA programs in AP-affiliated universities and colleges.",
    category: "general",
    state: "AP",
    priority: "medium",
    source: "APSCHE",
    sourceUrl: "https://cets.apsche.ap.gov.in/ICET/",
    tags: ["AP ICET", "MBA", "MCA", "Admit Card", "2026"],
  },
  // ── Updated: March 17, 2026 ────────────────────────────────────
  {
    id: "ap-eapcet-2026-result-admit-card-dates",
    date: "2026-03-17",
    title: "AP EAPCET 2026 — Result on June 1, Admit Card Available April 28",
    summary: "JNTU Kakinada has confirmed that AP EAPCET 2026 results will be declared on June 1, 2026. Admit cards will be available for download from April 28.",
    body: "Key upcoming dates for AP EAPCET 2026 candidates:\n\n• Application form correction window: March 26–28, 2026 (closed)\n• Admit card download: April 28, 2026 onwards at cets.apsche.ap.gov.in\n• Engineering exam: May 12, 13, 14, 15 & 18, 2026\n• Agriculture/Pharmacy exam: May 19 & 20, 2026\n• Result declaration: June 1, 2026\n\nCandidates can download their hall tickets using registration number or payment reference ID, qualifying exam hall ticket number, and date of birth. Keep the admit card safe — it is required throughout the admission process.\n\nNote: AP EAPCET 2026 application fees have been revised to ₹800 (General), ₹750 (BC), ₹700 (SC/ST) — a ₹200 increase across all categories.",
    category: "eapcet",
    state: "AP",
    priority: "high",
    source: "APSCHE Official Notification",
    sourceUrl: "https://cets.apsche.ap.gov.in/EAPCET/",
    tags: ["AP EAPCET", "Result Date", "Admit Card", "2026"],
  },
  {
    id: "iiit-hyderabad-ugee-2026-registration",
    date: "2026-03-17",
    title: "IIIT Hyderabad UGEE 2026 — Registration Closed, Exam on May 2",
    summary: "IIIT Hyderabad UGEE 2026 registration closed March 31. The entrance exam will be held on May 2.",
    body: "The International Institute of Information Technology, Hyderabad (IIIT-H) UGEE 2026 registration has closed.\n\n• Registration: Closed (deadline was March 31, 2026)\n• Exam date: May 2, 2026 (9:00 AM – 12:00 Noon)\n• Interview dates: June 4–6, 2026 (on campus)\n\nIIIT Hyderabad is one of the top CS/IT institutions in India. Admission is through UGEE scores + JEE Mains marks + interview. Registered candidates should prepare for the upcoming exam.\n\nCheck ugadmissions.iiit.ac.in for admit card updates.",
    category: "general",
    state: "TS",
    priority: "medium",
    source: "IIIT Hyderabad",
    sourceUrl: "https://ugadmissions.iiit.ac.in/ugee/",
    tags: ["IIIT Hyderabad", "UGEE", "Exam", "2026"],
  },
  {
    id: "gitam-gat-2026-march-phase",
    date: "2026-03-17",
    title: "GITAM GAT 2026 — March Phase Completed, Further Phases Available",
    summary: "GITAM GAT 2026 March phase exam (March 29) has been completed. Further admission phases are available throughout 2026.",
    body: "GITAM (Gandhi Institute of Technology and Management) GAT 2026 March phase has been completed.\n\n• March phase exam: Completed (March 29, 2026)\n• Results: Announced on the day of the exam\n• Campuses: Visakhapatnam (AP), Hyderabad (TS), Bengaluru\n\nGITAM conducts GAT in multiple phases throughout the admission season. Students who missed the March phase can register for upcoming phases at apply.gitam.edu.\n\nGITAM is a Deemed University with NAAC A++ accreditation, offering B.Tech programs across multiple branches. JEE Main score holders may be eligible for GAT waiver — check the GITAM admissions portal for details.",
    category: "general",
    state: "Both",
    priority: "low",
    source: "GITAM University",
    sourceUrl: "https://apply.gitam.edu/",
    tags: ["GITAM", "GAT", "Admission", "2026", "Visakhapatnam", "Hyderabad"],
  },
  {
    id: "bitsat-2026-registration-deadline",
    date: "2026-03-17",
    title: "BITSAT 2026 — Session 1 Completed, Session 2 Registration Open",
    summary: "BITSAT 2026 Session 1 (April 15–16) has been completed. Session 2 registration is open until May 2, exam on May 24–26.",
    body: "BITS Pilani BITSAT 2026 Session 1 has been completed.\n\n• Session 1 exam: Completed (April 15–16, 2026)\n• Admit cards for Session 1: Were released April 10\n• Session 2 registration: Open until May 2, 2026\n• Session 2 exam: May 24–26, 2026\n\nMajor update: Starting with the 2026–27 academic year, BITS Pilani has introduced tuition-blind admissions for the top 500 BITSAT rank holders, offering a four-year scholarship covering full tuition fees.\n\nStudents who missed Session 1 can still register for Session 2. BITS Pilani Hyderabad campus is a top choice for AP and TS engineering aspirants. Apply at admissions.bits-pilani.ac.in.",
    category: "general",
    state: "Both",
    priority: "medium",
    source: "BITS Pilani Admissions",
    sourceUrl: "https://admissions.bits-pilani.ac.in/",
    tags: ["BITSAT", "BITS Pilani", "Session 2", "Registration", "Scholarship", "2026"],
  },
  {
    id: "viteee-srmjeee-2026-deadlines",
    date: "2026-03-17",
    title: "VITEEE 2026 Exam Underway, SRMJEEE Phase 1 Revised to April 24–29",
    summary: "VITEEE 2026 registration closed April 12. Exam runs April 28–May 3. SRMJEEE Phase 1 revised to April 24–29.",
    body: "Updates on two major private university entrance exams:\n\nVITEEE 2026 (VIT Vellore, Chennai, AP-Amaravati, Bhopal):\n• Registration: Closed (extended deadline was April 12, 2026)\n• Exam dates: April 28 – May 3, 2026 (slot-based online)\n• VIT-AP (Amaravati) campus is relevant for AP students\n• Slot booking in progress at viteee.vit.ac.in\n\nSRMJEEE 2026 (SRM University):\n• Phase 1 exam: Revised to April 24–29, 2026 (remote proctored, home-based)\n• Phase 2: June 10–15 | Phase 3: July 4–5\n• No negative marking. Application fee: ₹1,400 per phase\n• Apply at applications.srmist.edu.in/btech\n\nBoth VIT and SRM are popular choices for AP/TS students seeking private university B.Tech admissions.",
    category: "general",
    state: "Both",
    priority: "medium",
    source: "VIT / SRM Official",
    sourceUrl: "https://viteee.vit.ac.in/",
    tags: ["VITEEE", "SRMJEEE", "VIT", "SRM", "Exam", "2026"],
  },

  // ── EAPCET 2026 ──────────────────────────────────────────────
  {
    id: "ap-eapcet-2026-deadline",
    date: "2026-03-17",
    title: "AP EAPCET 2026 — Last Date Extended Again to March 24 (No Late Fee)",
    summary: "APSCHE has extended the AP EAPCET 2026 registration deadline once more — apply without late fee by March 24, 2026.",
    body: "The Andhra Pradesh State Council of Higher Education (APSCHE) has extended the last date for AP EAPCET 2026 registration without late fee to March 24, 2026. This is the second extension (previously March 17).\n\nRevised late fee schedule:\n• ₹1,000 late fee: by March 28\n• ₹2,000 late fee: by April 1\n• ₹4,000 late fee: by April 6\n• ₹10,000 late fee: by April 10\n• Correction window: April 11–13\n\nApplication fee: ₹800 (General), ₹750 (BC), ₹700 (SC/ST). The exam is conducted by JNTU Kakinada on behalf of APSCHE. Apply at cets.apsche.ap.gov.in/EAPCET.",
    category: "eapcet",
    state: "AP",
    priority: "high",
    source: "APSCHE Official Notification",
    sourceUrl: "https://cets.apsche.ap.gov.in/EAPCET/",
    tags: ["AP EAPCET", "Registration", "Deadline", "2026"],
  },
  {
    id: "ap-eapcet-2026-exam-dates",
    date: "2026-02-04",
    title: "AP EAPCET 2026 Exam Dates Announced — Engineering: May 12–18",
    summary: "APSCHE has released the full AP EAPCET 2026 schedule. Engineering exam on May 12, 13, 14, 15 & 18. Agriculture/Pharmacy on May 19 & 20.",
    body: "The AP-CETs 2026 notification was issued on February 3, 2026 by the Secretary of APSCHE, Guntur. AP EAPCET (APEAPCET) 2026 for Engineering will be conducted by JNTU Kakinada on May 12, 13, 14, 15, and 18, 2026. The Agriculture & Pharmacy stream exam (APECET) will be conducted by JNTU Anantapur on April 23, 2026.\n\nAll AP CETs 2026 will be conducted through Computer Based Test (CBT) mode. Registration opened February 4, 2026.\n\nOther AP CETs: APICET (May 2), APPGECET (April 28–30), APLAWCET (May 4), APEDCET (May 4), APPGCET (May 8–11), APPECET (June 3).",
    category: "eapcet",
    state: "AP",
    priority: "high",
    source: "APSCHE Official Notification (03.02.2026)",
    sourceUrl: "https://cets.apsche.ap.gov.in/EAPCET/",
    tags: ["AP EAPCET", "Exam Dates", "2026", "AP CETs"],
  },
  {
    id: "ts-eapcet-2026-registration",
    date: "2026-02-19",
    title: "TG EAPCET 2026 Registration Open — Apply by April 4 Without Late Fee",
    summary: "Telangana EAPCET 2026 application forms are live. Last date without late fee is April 4, 2026. Exam: May 4–11.",
    body: "JNTU Hyderabad, on behalf of TGCHE, has opened online registration for TG EAPCET 2026 from February 19, 2026. Candidates can apply without late fee until April 4, 2026.\n\nLate fee schedule: ₹250 (by April 10), ₹500 (by April 15), ₹2,500 (by April 20), ₹5,000 (by April 24), ₹10,000 (by May 2).\n\nApplication fee: ₹900 (General, single stream), ₹1,800 (both streams), ₹500/₹1,000 (SC/ST/PH).\n\nExam dates — Agriculture & Pharmacy: May 4–5; Engineering: May 9–11 (two shifts per day: 9 AM–12 PM and 3–6 PM).\n\nApply at eapcet.tgche.ac.in.",
    category: "eapcet",
    state: "TS",
    priority: "high",
    source: "TGCHE / JNTUH Official Notification",
    sourceUrl: "https://eapcet.tgche.ac.in/",
    tags: ["TS EAPCET", "TG EAPCET", "Registration", "2026"],
  },
  {
    id: "ts-eapcet-2026-marks-vs-rank",
    date: "2026-02-19",
    title: "TG EAPCET 2026 — Marks vs Rank Band Reference (2024 & 2025 Data)",
    summary: "Official normalization marks vs rank band data released for TG EAPCET 2026 based on 2024 and 2025 performance.",
    body: "The TG EAPCET 2026 convener has published marks-vs-rank reference tables based on TG EAPCET 2024 and 2025 data.\n\nEngineering (2025): 80+ marks → below rank 2,613 | 75+ → 2,614–3,995 | 70+ → 3,996–6,104 | 65+ → 6,105–9,226 | 60+ → 9,227–14,418 | 55+ → 14,419–24,028 | 50+ → 24,029–44,121 | 45+ → 44,122–82,343 | 40+ → 82,344–1,35,462.\n\nAgriculture & Pharmacy (2025): 80+ → below 2,726 | 70+ → 4,629–7,182 | 60+ → 10,537–15,011 | 50+ → 21,745–32,151 | 40+ → 46,573–61,764.\n\nNote: These are based on normalized marks out of 160.",
    category: "eapcet",
    state: "TS",
    priority: "medium",
    source: "TG EAPCET 2026 Convener",
    sourceUrl: "https://eapcet.tgche.ac.in/",
    tags: ["TS EAPCET", "Marks vs Rank", "Reference", "2026"],
  },

  // ── Counselling & Admissions ──────────────────────────────────
  {
    id: "ap-eapcet-2026-counselling-preview",
    date: "2026-03-14",
    title: "AP EAPCET 2026 Counselling Expected July 2026 — What to Expect",
    summary: "AP EAPCET 2026 counselling is expected to begin in the first week of July 2026 with 2 rounds of web counselling.",
    body: "Based on previous years' schedules, AP EAPCET 2026 counselling is expected to start in the 1st week of July 2026. The process will include:\n\n1. Online registration and slot booking\n2. Certificate verification at designated Help Line Centers\n3. Web options entry (choosing colleges and branches)\n4. Seat allotment (2 rounds + spot round)\n5. Reporting to allotted college\n\nCounselling registration fee: ₹1,200 (OC/BC), ₹600 (SC/ST).\n\nCategory-A (Convener Quota): ~70% of seats filled via APSCHE counselling.\nCategory-B (Management Quota): ~30% — fees regulated by APHERMC.",
    category: "counselling",
    state: "AP",
    priority: "low",
    source: "APSCHE",
    sourceUrl: "https://cets.apsche.ap.gov.in/EAPCET/",
    tags: ["Counselling", "AP EAPCET", "2026", "Admissions"],
  },
  {
    id: "ts-eapcet-2026-counselling-preview",
    date: "2026-03-14",
    title: "TS EAPCET 2026 Counselling Expected July–August 2026",
    summary: "Telangana EAPCET counselling typically runs July–August with 3 rounds + 1 special round.",
    body: "TS EAPCET 2026 counselling is expected to begin in July 2026, running through August. Based on previous years:\n\n• 3 regular rounds + 1 special round\n• Convener quota: 70% of seats filled via TSCHE web counselling\n• Minimum qualifying marks: 25% (40 out of 160)\n• Registration fee: ₹1,200 (unreserved), ₹600 (reserved categories)\n\nCounselling will be conducted through the TSCHE website. Candidates need to register, verify documents, enter web options, and report to allotted college within the specified timeline.\n\nFee regulation: TS AFRC (block period system, currently 2025–28 per G.O. Ms. No. 06).",
    category: "counselling",
    state: "TS",
    priority: "low",
    source: "TSCHE",
    sourceUrl: "https://eapcet.tgche.ac.in/",
    tags: ["Counselling", "TS EAPCET", "2026", "Admissions"],
  },

  // ── Other CETs ────────────────────────────────────────────────
  {
    id: "tg-pgecet-2026",
    date: "2026-02-27",
    title: "TG PGECET 2026 Applications Open — M.Tech, M.Pharm, M.Arch Admissions",
    summary: "Applications for Telangana PGECET 2026 (M.E/M.Tech, M.Pharm, M.Arch, Pharm.D) are open from February 27 for AY 2026–27.",
    body: "The Telangana Post Graduate Engineering Common Entrance Test (TG PGECET) 2026 applications have opened from February 27, 2026, for admissions into M.E/M.Tech, M.Pharm, M.Arch, and Pharm.D courses for the 2026–27 academic year.\n\nThis is relevant for students who have completed their B.Tech/B.E. and are looking to pursue higher education in Telangana.",
    category: "general",
    state: "TS",
    priority: "low",
    source: "TGCHE",
    sourceUrl: "https://eapcet.tgche.ac.in/",
    tags: ["PGECET", "M.Tech", "Telangana", "2026"],
  },
  {
    id: "ap-ecet-2026",
    date: "2026-03-14",
    title: "AP ECET 2026 — Lateral Entry Engineering Applications Open",
    summary: "AP ECET 2026 applications are open for lateral entry admissions into engineering and pharmacy programs.",
    body: "Applications for AP ECET (Engineering Common Entrance Test) 2026 are open for diploma holders and B.Sc degree holders seeking lateral entry into B.Tech/B.Pharm second year. This is conducted by Acharya Nagarjuna University on behalf of APSCHE.\n\nPhysical Efficiency and Games Skill Test commences on June 3, 2026. Registration started February 13, 2026.",
    category: "general",
    state: "AP",
    priority: "low",
    source: "APSCHE",
    sourceUrl: "https://cets.apsche.ap.gov.in/",
    tags: ["AP ECET", "Lateral Entry", "2026"],
  },

  // ── NAAC / NIRF ───────────────────────────────────────────────
  {
    id: "nirf-naac-2026-status",
    date: "2026-03-14",
    title: "NIRF 2026 Rankings & NAAC Updates — Not Yet Released",
    summary: "NIRF 2026 rankings are expected later in 2026. No new NAAC accreditations for AP/TS colleges announced yet.",
    body: "As of March 14, 2026:\n\n• NIRF 2026 rankings have NOT been released yet. Expected mid-to-late 2026.\n• NAAC A++ updated list for 2026 is expected around August 2026 — no new cycle completions announced.\n• No new NAAC accreditations specifically for AP or TS engineering colleges were found.\n• Notable existing: Andhra University holds NAAC A++ grade. NALSAR (Hyderabad) holds NAAC A++ (CGPA 3.52).\n\nTeluguColleges.com NAAC data reflects the latest available grades.",
    category: "naac-nirf",
    state: "Both",
    priority: "low",
    source: "NAAC / NIRF",
    tags: ["NIRF", "NAAC", "Rankings", "2026"],
  },
];

// Helper to get the latest N news items
export function getLatestNews(n: number = 10): NewsItem[] {
  return [...NEWS_ITEMS].sort((a, b) => b.date.localeCompare(a.date)).slice(0, n);
}

// Helper to filter by state
export function getNewsByState(state: "AP" | "TS" | "Both"): NewsItem[] {
  return NEWS_ITEMS.filter(n => n.state === state || n.state === "Both")
    .sort((a, b) => b.date.localeCompare(a.date));
}

// Helper to filter by category
export function getNewsByCategory(category: NewsItem["category"]): NewsItem[] {
  return NEWS_ITEMS.filter(n => n.category === category)
    .sort((a, b) => b.date.localeCompare(a.date));
}

// Category metadata
export const NEWS_CATEGORIES: { key: NewsItem["category"]; label: string; color: string; bgColor: string }[] = [
  { key: "eapcet", label: "EAPCET 2026", color: "text-blue-700", bgColor: "bg-blue-50" },
  { key: "fees", label: "Fees", color: "text-emerald-700", bgColor: "bg-emerald-50" },
  { key: "counselling", label: "Counselling", color: "text-purple-700", bgColor: "bg-purple-50" },
  { key: "naac-nirf", label: "NAAC / NIRF", color: "text-amber-700", bgColor: "bg-amber-50" },
  { key: "general", label: "General", color: "text-gray-700", bgColor: "bg-gray-100" },
];
