export interface NewsItem {
  id: string;
  date: string; // YYYY-MM-DD
  title: string;
  summary: string;
  body: string; // HTML-safe plain text with line breaks
  category: "eapcet" | "fees" | "counselling" | "naac-nirf" | "general";
  state: "AP" | "TS" | "Both";
  priority: "high" | "medium" | "low";
  source?: string;
  sourceUrl?: string;
  tags: string[];
}

export const NEWS_ITEMS: NewsItem[] = [
  // ── New: May 29, 2026 ─────────────────────────────────────────
  {
    id: "re-neet-2026-city-slip-may-31-admit-card-june-14",
    date: "2026-05-29",
    title: "Re-NEET 2026 — City Intimation Slip Expected by May 31; Admit Card June 14",
    summary: "NTA is expected to release the Re-NEET 2026 city intimation slip by May 31, 2026 at neet.nta.nic.in. Admit card follows on June 14. The re-exam is on June 21, 2026 (2:00–5:15 PM) for all 22.79 lakh candidates affected by the May 3 paper-leak cancellation.",
    body: "The National Testing Agency (NTA) is expected to release the Re-NEET UG 2026 city intimation slip at neet.nta.nic.in by May 31, 2026 — roughly three weeks ahead of the re-exam. The advance city slip lets candidates plan travel and accommodation; the actual exam centre address is shared only on the admit card.\n\nKey dates:\n• City intimation slip: Expected by May 31, 2026 at neet.nta.nic.in\n• Admit card release: Expected June 14, 2026\n• Re-exam (Re-NEET 2026): June 21, 2026 (Saturday)\n• Exam timing: 2:00 PM – 5:15 PM (15 minutes extra vs the original NEET UG)\n• Mode: Pen-and-paper\n• Fee refund window (for candidates not appearing in the re-exam): Extended to June 22, 2026\n\nBackground: NTA cancelled the May 3, 2026 NEET UG exam after a CBI-confirmed paper leak. All 22,79,743 originally registered candidates are eligible for Re-NEET 2026. The re-exam is being held in pen-and-paper mode at NTA-designated centres across India.\n\nHow to download the city slip:\n1. Visit neet.nta.nic.in\n2. Click the advance city intimation link for Re-NEET 2026\n3. Log in with application number + DOB / password\n4. Download and save the slip — it shows only the allotted city, not the exact centre\n\nFor AP/TS aspirants: NEET UG 2026 scores remain the sole criterion for MBBS/BDS admissions at Dr. NTR UHS (AP) and KNRUHS (Telangana), plus 15% AIQ (MCC) and deemed universities. State counselling is now expected to begin in late July / August 2026, after the Re-NEET result.\n\nFrom 2027 onwards, NEET UG will shift to Computer-Based Test (CBT) mode to prevent paper leaks, as announced by the Union Education Minister.",
    category: "general",
    state: "Both",
    priority: "high",
    source: "NTA — Re-NEET 2026 City Intimation / Admit Card Notice",
    sourceUrl: "https://neet.nta.nic.in/",
    tags: ["NEET UG", "Re-NEET", "City Intimation", "Admit Card", "NTA", "June 21", "2026"],
  },
  // ── New: May 27, 2026 ─────────────────────────────────────────
  {
    id: "josaa-2026-registration-opens-june-2",
    date: "2026-05-27",
    title: "JoSAA 2026 — IIT/NIT/IIIT/GFTI Counselling Registration Opens June 2",
    summary: "JoSAA 2026 counselling registration will open on June 2, 2026 at josaa.nic.in — one day after the JEE Advanced 2026 result. Six rounds across IITs, NITs, IIITs and GFTIs. AP/TS aspirants targeting IIT Hyderabad should keep documents ready.",
    body: "The Joint Seat Allocation Authority (JoSAA) has confirmed the JEE Advanced 2026 schedule and will open JoSAA 2026 counselling registration on June 2, 2026 at josaa.nic.in — one day after the JEE Advanced 2026 result is declared on June 1.\n\nKey points:\n• Registration opens: June 2, 2026 at josaa.nic.in\n• Total rounds: 6 (each round = seat allotment → online acceptance → online reporting + fee payment → document upload)\n• Participating institutes: 23 IITs (seat allotment based on JEE Advanced rank) + 31 NITs + 26 IIITs + 47 GFTIs (seat allotment based on JEE Main rank)\n• Choice-filling: Opens shortly after registration; candidates can lock as many institute–branch preferences as they wish, in priority order\n• Eligibility: JEE Main 2026 (any session) rank for NITs/IIITs/GFTIs; top 2,50,182 JEE Main qualifiers + JEE Advanced 2026 rank for IITs\n• Reporting fee: ₹35,000 (general) / ₹20,000 (SC/ST/PwD) — adjustable against tuition fee after final allotment\n\nFor AP/TS aspirants:\n• IIT Hyderabad remains the most popular IIT for Telugu-state candidates, followed by IIT Madras, Bombay and Roorkee\n• NIT Warangal (TS) and NIT Andhra Pradesh (Tadepalligudem) participate via JEE Main rank\n• IIIT Hyderabad (UGEE-based) and IIIT Sri City fill seats outside JoSAA — separate processes\n• CSAB special rounds follow JoSAA closure for left-over NIT+ seats\n\nDocuments to keep ready (scanned + originals for online reporting):\n• Class X and XII marksheets and pass certificates\n• Photo ID (Aadhaar preferred)\n• Category certificate (OBC-NCL / SC / ST / EWS) issued in the prescribed JoSAA format\n• PwD certificate (if applicable)\n• Passport-size photograph matching the application\n• JEE Main and (for IITs) JEE Advanced scorecards\n\nWatch josaa.nic.in for the full round-wise calendar — typically released alongside the JEE Advanced result on June 1. JoSAA round 1 allotment historically follows within 7–10 days of registration opening.",
    category: "counselling",
    state: "Both",
    priority: "high",
    source: "Joint Seat Allocation Authority (JoSAA) / JEE (Advanced) 2026 — IIT Roorkee",
    sourceUrl: "https://josaa.nic.in/",
    tags: ["JoSAA", "IIT", "NIT", "IIIT", "GFTI", "Counselling", "JEE Advanced", "2026"],
  },
  // ── New: May 25, 2026 ─────────────────────────────────────────
  {
    id: "ap-eapcet-2026-preliminary-key-released-may-25",
    date: "2026-05-25",
    title: "AP EAPCET 2026 — Preliminary Answer Key Released; Objection Window Closes May 27 at 11 AM",
    summary: "JNTU Kakinada released the AP EAPCET 2026 preliminary answer key at 11 AM on May 25 at cets.apsche.ap.gov.in. Candidate response sheets were already live. Objections can be raised online until 11 AM on May 27, 2026. Final result: June 1, 2026.",
    body: "The Andhra Pradesh Engineering, Agriculture and Pharmacy Common Entrance Test (AP EAPCET) 2026 preliminary answer key has been released by JNTU Kakinada at 11:00 AM on May 25, 2026 at cets.apsche.ap.gov.in.\n\nKey points (per AP EAPCET-2026 convener Prof. N. Mohan Rao):\n• Preliminary key release: May 25, 2026 at 11:00 AM (revised from the earlier May 23 indication)\n• Candidate response sheets: Already uploaded on the official portal\n• Objection window: Open until May 27, 2026 at 11:00 AM\n• Objections accepted via: https://cets.apsche.ap.gov.in (login with hall ticket + DOB)\n• Final result + rank card: June 1, 2026\n\nThe AP EAPCET 2026 examination was conducted successfully in CBT mode from May 12 to May 20, 2026 across Andhra Pradesh and Hyderabad (Engineering: May 12, 13, 14, 15 & 18; Agriculture/Pharmacy: May 19–20), as confirmed by AP EAPCET 2026 chairman and JNTUK Vice-Chancellor Prof. C.S.R.K. Prasad.\n\nHow to raise an objection: Download the preliminary key and your response sheet from the candidate login, identify any disputed question, then submit the challenge via the \"Key Objections\" link with the question ID, a clear reason, and supporting evidence (textbook reference, derivation, etc.). APSCHE / JNTUK will review every objection before publishing the final answer key alongside the result on June 1.\n\nWhat to do now: Save your response sheet immediately, cross-check with the preliminary key, and file objections only with citable evidence before the 11 AM, May 27 deadline. AP EAPCET 2026 counselling is expected to start in the first week of July 2026 with two regular rounds plus a spot round, conducted by APSCHE.",
    category: "eapcet",
    state: "AP",
    priority: "high",
    source: "APSCHE / JNTU Kakinada — AP EAPCET 2026 Preliminary Key Notice (DC Correspondent, 23.05.2026)",
    sourceUrl: "https://cets.apsche.ap.gov.in/EAPCET/",
    tags: ["AP EAPCET", "Answer Key", "Preliminary Key", "Objections", "May 25", "2026"],
  },
  {
    id: "jee-advanced-2026-provisional-key-released-may-25",
    date: "2026-05-25",
    title: "JEE Advanced 2026 — Provisional Answer Key Released; Objections Open Till 5 PM, May 26",
    summary: "IIT Roorkee released the JEE Advanced 2026 provisional answer key for Paper 1 and Paper 2 at 10 AM on May 25 at jeeadv.ac.in. Candidates can raise objections until 5:00 PM on May 26, 2026. Final answer key and result: June 1, 2026 at 10 AM.",
    body: "IIT Roorkee, the organising institute for JEE Advanced 2026, released the provisional answer key for both Paper 1 and Paper 2 at 10:00 AM on Monday, May 25, 2026 at jeeadv.ac.in.\n\n• Provisional answer key release: May 25, 2026 at 10:00 AM IST\n• Papers covered: Paper 1 + Paper 2 (both compulsory)\n• Candidate response sheets: Released earlier on May 21, 2026\n• Objection window: May 25 (10:00 AM) — May 26, 2026 (5:00 PM IST)\n• Final answer key + result: June 1, 2026 at 10:00 AM IST\n• Architecture Aptitude Test (AAT) registration: Opens after the result\n\nApproximately 1.5 lakh engineering aspirants — the top JEE Main 2026 qualifiers — appeared in JEE Advanced 2026 on May 17, 2026. The answer key lets candidates cross-check their marked responses against the official answers and estimate probable scores ahead of the JoSAA 2026 IIT counselling.\n\nHow to raise an objection: Log in at jeeadv.ac.in using the JEE Advanced registration number and date of birth, open the Provisional Answer Key Challenge link, select the disputed question(s), upload supporting material and pay the per-question challenge fee. All challenges are reviewed by IIT Roorkee before the final key is published with the result on June 1.\n\nFor AP/TS aspirants: JoSAA 2026 counselling for IITs/NITs/IIITs/GFTIs typically begins within a week of the JEE Advanced result and runs 5–6 rounds in June–July. IIT Hyderabad continues to be the most popular IIT for Telugu-state candidates, followed by IIT Madras, Bombay and Roorkee.",
    category: "general",
    state: "Both",
    priority: "high",
    source: "JEE (Advanced) 2026 — IIT Roorkee Provisional Answer Key Notice",
    sourceUrl: "https://jeeadv.ac.in/",
    tags: ["JEE Advanced", "IIT Roorkee", "Answer Key", "Objections", "May 25", "2026"],
  },
  // ── New: May 20, 2026 ─────────────────────────────────────────
  {
    id: "neet-ug-2026-cancelled-re-exam-june-21",
    date: "2026-05-20",
    title: "NEET UG 2026 Cancelled Due to Paper Leak — Re-Exam Scheduled for June 21",
    summary: "NTA has cancelled the NEET UG 2026 exam held on May 3 after a confirmed question paper leak. A fresh re-exam (Re-NEET 2026) will be conducted on June 21, 2026 for all 22.79 lakh registered candidates. CBI is investigating.",
    body: "The National Testing Agency (NTA) has cancelled the NEET UG 2026 examination that was conducted on May 3, 2026 following confirmation of a question paper leak. The Central Bureau of Investigation (CBI) has taken over the probe.\n\nKey developments:\n• A PDF containing approximately 500–600 questions had circulated on Telegram from April 29, 2026 — days before the exam. Around 180 questions were reported to match the actual NEET UG 2026 paper.\n• CBI arrested multiple suspects including a biology lecturer who was part of the NTA paper-setting committee.\n• The CBI has indicated the leak can be traced to a source inside the NTA itself.\n\nRe-NEET 2026 schedule:\n• Re-exam date: June 21, 2026 (Saturday)\n• Timing: 2:00 PM – 5:15 PM (15 minutes extra compared to the original exam)\n• Mode: Pen-and-paper\n• City choice filling / correction window: Open until May 21, 2026 at neet.nta.nic.in\n• Admit card: Expected by June 14, 2026\n• Exam fee: Will be refunded to original bank accounts of payers for the cancelled May 3 exam\n• All 22,79,743 registered candidates are eligible to appear\n\nFor AP/TS aspirants: The NEET UG 2026 result timeline is now delayed. State counselling for MBBS/BDS at Dr. NTR UHS (AP) and KNRUHS (Telangana) will begin only after the Re-NEET result, now expected in July 2026 instead of June.\n\nEducation Minister Dharmendra Pradhan has announced that NEET UG will shift to Computer-Based Test (CBT) mode from 2027 onwards to prevent future paper leaks.",
    category: "general",
    state: "Both",
    priority: "high",
    source: "NTA / CBI — NEET UG 2026 Cancellation and Re-Exam Notice",
    sourceUrl: "https://neet.nta.nic.in/",
    tags: ["NEET UG", "Cancelled", "Paper Leak", "Re-Exam", "CBI", "NTA", "June 21", "2026"],
  },
  {
    id: "ts-ecet-2026-answer-key-released-may-20",
    date: "2026-05-20",
    title: "TS ECET 2026 — Answer Key Released, Objection Window Closes May 20 at 7 PM",
    summary: "Osmania University has released the TS ECET 2026 provisional answer key, response sheets and question papers at ecet.tgche.ac.in. Candidates can raise objections until May 20, 2026 at 7:00 PM. Result expected in June 2026.",
    body: "The provisional answer key, candidate response sheets and master question papers for TS (TG) ECET 2026 have been released by Osmania University at ecet.tgche.ac.in.\n\n• Exam conducted: May 15, 2026 (CBT mode)\n• Answer key released: May 2026\n• Last date to raise objections: May 20, 2026 at 7:00 PM\n• Objection submission: Via the official portal (login with registration number and DOB)\n• Result: Expected June 2026\n• Counselling: Typically July–August 2026\n\nCandidates should download their response sheets and cross-check with the provisional key before the objection deadline. The final answer key will be published along with the result after reviewing all objections.\n\nTS ECET is the lateral-entry test for diploma holders and B.Sc graduates seeking direct admission into the second year of B.Tech / B.Pharm programmes in Telangana.",
    category: "general",
    state: "TS",
    priority: "medium",
    source: "TGCHE / Osmania University — TS ECET 2026 Answer Key",
    sourceUrl: "https://ecet.tgche.ac.in/",
    tags: ["TS ECET", "TG ECET", "Answer Key", "Lateral Entry", "2026"],
  },
  // ── New: May 19, 2026 ─────────────────────────────────────────
  {
    id: "ap-eapcet-2026-engineering-exam-concluded-may-18",
    date: "2026-05-19",
    title: "AP EAPCET 2026 — Engineering Exam Concludes May 18; Preliminary Key Rescheduled to May 25",
    summary: "AP EAPCET 2026 Engineering was conducted across five days (May 12, 13, 14, 15 & 18). The preliminary answer key release was later rescheduled from May 23 to May 25, 2026 at 11 AM (see the May 25 update); objection window now closes May 27 at 11 AM. Final result: June 1, 2026.",
    body: "JNTU Kakinada has successfully concluded the AP EAPCET 2026 Engineering examination on May 18, 2026. The exam was held over five days (May 12, 13, 14, 15 and 18) in two daily shifts of three hours each.\n\nNext steps (revised — see May 25 update for the latest):\n• Preliminary answer key + individual response sheets: May 25, 2026 at 11:00 AM at cets.apsche.ap.gov.in (revised from the earlier May 23 indication; response sheets went live before that)\n• Objection window: Open until May 27, 2026 at 11:00 AM\n• Final result + rank card: June 1, 2026\n• Agriculture/Pharmacy (APECET) stream: May 19–20, 2026\n\nHow objections work: After downloading the preliminary key from the candidate login (hall ticket + DOB), students can challenge any question via the \"Key Objections\" link. Each objection must include the disputed question ID, a clear reason and supporting evidence (textbook scan, derivation, etc.) — APSCHE / JNTUK will review all objections before publishing the final key alongside the result.\n\nWhat to do now: Download and save your response sheet; cross-check with the preliminary key; raise objections only with citable evidence before the 11 AM, May 27 deadline. AP EAPCET counselling is expected to begin in the first week of July 2026, conducted by APSCHE in two regular rounds plus a spot round. Convener-quota fees for the 2025–28 block are governed by APHERMC; management-quota fees by individual colleges.",
    category: "eapcet",
    state: "AP",
    priority: "high",
    source: "APSCHE / JNTU Kakinada — AP EAPCET 2026 Schedule",
    sourceUrl: "https://cets.apsche.ap.gov.in/EAPCET/",
    tags: ["AP EAPCET", "Engineering", "Answer Key", "Result", "2026"],
  },
  // ── New: May 17, 2026 ─────────────────────────────────────────
  {
    id: "tg-eapcet-2026-results-declared-may-17",
    date: "2026-05-17",
    title: "TG EAPCET 2026 Results Declared — 77.25% Qualified; M Rushi (Medchal) Tops Engineering",
    summary: "TGCHE and JNTU Hyderabad declared TG EAPCET 2026 results on May 17 at 11 AM. Out of 2,82,195 candidates, 2,18,998 qualified (77.25%). Engineering topper: M Rushi (Medchal–Malkajgiri) with 156.63 marks. Agriculture & Pharmacy topper: Mukkaram Ahmed (Hyderabad) with 150.18 marks.",
    body: "The Telangana Council of Higher Education (TGCHE) and JNTU Hyderabad released the TG EAPCET 2026 results on Sunday, May 17, 2026 at 11:00 AM at Golden Jubilee Hall, JNTUH. The results were declared by Advisor (Public Affairs) K. Keshava Rao, Secretary (Education) Yogita Rana, TGCHE Chairman V. Balakista Reddy and other officials.\n\nOverall statistics:\n• Total candidates appeared: 2,82,195\n• Total candidates qualified: 2,18,998\n• Overall pass percentage: 77.25%\n\nStream-wise:\n• Engineering — 1,97,242 appeared, 1,44,704 qualified (73.36%)\n• Agriculture & Pharmacy — 84,954 appeared, 73,294 qualified (86.27%)\n\nTop rankers:\n• Engineering AIR 1: M. Rushi — 156.6353 marks (Medchal–Malkajgiri, Telangana)\n• Engineering AIR 2: Bejugama Anshul — 148.7082 marks (Medchal, Telangana)\n• Agriculture & Pharmacy AIR 1: Mukkaram Ahmed — 150.1771 marks (Hyderabad)\n\nHow to download: Candidates can log in at eapcet.tgche.ac.in using registration number, hall ticket number and date of birth. The rank card lists subject-wise marks, normalised score, percentile and overall rank.\n\nWhat's next: TG EAPCET 2026 counselling is expected to begin in late June – early July 2026 with three regular rounds plus a special round. Convenor-quota tuition fees for 2025–26 to 2027–28 are now locked under G.O. Ms. No. 06 (₹45,000 floor, ₹1,83,000 ceiling at CBIT). Candidates should prepare originals: SSC, Inter memos, TC, study certificates, caste certificate (if applicable), income certificate, EWS certificate (if applicable) and Aadhaar.",
    category: "eapcet",
    state: "TS",
    priority: "high",
    source: "TGCHE / JNTU Hyderabad — TG EAPCET 2026 Result Notification",
    sourceUrl: "https://eapcet.tgche.ac.in/",
    tags: ["TG EAPCET", "TS EAMCET", "Results", "Toppers", "M Rushi", "2026"],
  },
  {
    id: "jee-advanced-2026-exam-concluded-may-17",
    date: "2026-05-17",
    title: "JEE Advanced 2026 Conducted by IIT Roorkee on May 17 — Result on June 1",
    summary: "IIT Roorkee successfully conducted JEE Advanced 2026 on May 17 in two papers. Question papers and response sheets are now public at jeeadv.ac.in. Provisional answer key was released on May 25 (see May 25 update); final result: June 1, 2026.",
    body: "JEE Advanced 2026, the gateway to all 23 IITs, was conducted on Sunday, May 17, 2026 by IIT Roorkee (the zonal coordinator for 2026). Both papers were held in CBT mode.\n\n• Paper 1: 09:00–12:00 (48 questions reported)\n• Paper 2: 14:30–17:30 (54 questions reported)\n• Both papers compulsory\n\nPost-exam milestones:\n• Question papers: Released on the day of the exam at jeeadv.ac.in\n• Candidate response sheets: Released May 21, 2026\n• Provisional answer key: Released May 25, 2026 at 10:00 AM (see the May 25 update for objection details)\n• Objection window: Through May 26, 2026 at 5:00 PM\n• Final answer key: Along with result\n• Result: June 1, 2026 at 10:00 AM\n• Architecture Aptitude Test (AAT) registration: Opens after JEE Advanced result\n\nInformal student feedback (subject to verification with the official key): Physics was reported to be the toughest section in Paper 1, while Mathematics felt the most challenging in Paper 2. The cutoff for IIT counselling (JoSAA 2026) will be confirmed with the result.\n\nFor AP/TS aspirants: IIT Hyderabad continues to be the most popular IIT for Telugu-state candidates, followed by IIT Madras, Bombay and Roorkee. JoSAA counselling typically begins within a week of the JEE Advanced result and runs 5–6 rounds in June–July.",
    category: "general",
    state: "Both",
    priority: "high",
    source: "JEE (Advanced) 2026 — IIT Roorkee",
    sourceUrl: "https://jeeadv.ac.in/",
    tags: ["JEE Advanced", "IIT Roorkee", "IIT", "Result", "2026"],
  },
  // ── New: May 16, 2026 ─────────────────────────────────────────
  {
    id: "ap-icet-2026-results-may-16",
    date: "2026-05-16",
    title: "AP ICET 2026 Results Declared — 91.41% Qualified; Rank Cards Out",
    summary: "APSCHE declared AP ICET 2026 results on May 16 at cets.apsche.ap.gov.in. Of 23,198 candidates who appeared, 21,205 qualified — a pass percentage of 91.41%. MBA/MCA counselling expected in June–July.",
    body: "The Andhra Pradesh State Council of Higher Education (APSCHE) released the AP ICET 2026 results on May 16, 2026.\n\n• Total candidates appeared: 23,198\n• Total candidates qualified: 21,205\n• Pass percentage: 91.41%\n• Exam conducted on: May 2, 2026\n• Rank card download: cets.apsche.ap.gov.in/ICET (login with hall ticket + DOB)\n\nAP ICET is conducted by APSCHE for admission into MBA and MCA programmes across Andhra Pradesh universities and affiliated colleges (Andhra University, SVU, ANU, KU, JNTU-K, JNTU-A and their constituent/affiliated colleges).\n\nNext steps:\n• Download and save the rank card and scorecard\n• Watch for the AP ICET 2026 counselling notification (expected June–July 2026)\n• Keep originals ready: degree certificate, marks memos, transfer certificate, caste/income/EWS certificates as applicable, Aadhaar\n\nCategory-wise qualifying marks: General/BC must secure at least 25% (50 out of 200). SC/ST candidates are eligible for ranking based on any score.",
    category: "general",
    state: "AP",
    priority: "medium",
    source: "APSCHE — AP ICET 2026 Result Notification",
    sourceUrl: "https://cets.apsche.ap.gov.in/ICET/",
    tags: ["AP ICET", "MBA", "MCA", "Results", "2026"],
  },
  // ── New: May 15, 2026 ─────────────────────────────────────────
  {
    id: "tg-ecet-2026-exam-conducted-may-15",
    date: "2026-05-15",
    title: "TS ECET 2026 Conducted on May 15 — Answer Key Now Released (See May 20 Update)",
    summary: "Osmania University conducted TS (TG) ECET 2026 on May 15, 2026 in CBT mode. The provisional answer key, response sheets and question papers have been released. Objection window closes May 20 at 7 PM. Result expected June 2026.",
    body: "Osmania University, on behalf of the Telangana Council of Higher Education (TGCHE), successfully conducted TS (TG) ECET 2026 — the lateral-entry test for diploma holders and B.Sc graduates seeking direct admission into the second year of B.Tech / B.Pharm programmes in Telangana — on May 15, 2026 in CBT mode.\n\n• Eligibility streams: Diploma in Engineering / B.Sc Mathematics graduates for lateral B.Tech; Diploma in Pharmacy for lateral B.Pharm\n• Official portal: ecet.tgche.ac.in\n• Provisional answer key + response sheet: Expected within 7–10 days\n• Result: Expected late May / early June 2026\n• Counselling: Typically July–August 2026 (after main TG EAPCET counselling concludes)\n\nCandidates should keep their diploma/B.Sc marks memos, SSC certificate, study/conduct certificate, caste certificate (if applicable) and Aadhaar ready for the counselling document-verification stage. Lateral-entry seats are filled in the 10% supernumerary quota over and above the sanctioned intake of each engineering branch.",
    category: "general",
    state: "TS",
    priority: "medium",
    source: "TGCHE / Osmania University — TS ECET 2026",
    sourceUrl: "https://ecet.tgche.ac.in/",
    tags: ["TS ECET", "TG ECET", "Lateral Entry", "2026"],
  },
  // ── New: May 14, 2026 ─────────────────────────────────────────
  {
    id: "ap-pgecet-2026-results-may-14",
    date: "2026-05-14",
    title: "AP PGECET 2026 Results Released — Rank Cards Available",
    summary: "Andhra University, on behalf of APSCHE, declared AP PGECET 2026 results on May 14. Candidates can download rank cards at cets.apsche.ap.gov.in. Counselling expected with AP EAPCET counselling in July–August.",
    body: "Andhra University (Visakhapatnam), conducting body for AP PGECET on behalf of APSCHE, released the AP PGECET 2026 results on May 14, 2026.\n\n• Exam dates: April 28, 29 & 30, 2026 (CBT, two daily sessions)\n• For admissions to: M.E/M.Tech, M.Pharm, M.Arch, Pharm.D (PB)\n• Rank card download: cets.apsche.ap.gov.in/PGECET (registration number + AP PGECET hall ticket + DOB)\n\nQualifying criteria:\n• General/BC: 25% (30 out of 120) minimum\n• SC/ST: No minimum — eligible for ranking based on any score\n\nThe rank card shows marks secured, qualifying status, AP PGECET rank and percentile. AP PGECET 2026 counselling is expected to run alongside AP EAPCET counselling in July–August 2026. Candidates holding both a valid GATE score and AP PGECET qualification have an edge — GATE-qualified seats are filled first in M.Tech counselling, with PGECET ranks filling the remaining seats.",
    category: "general",
    state: "AP",
    priority: "low",
    source: "APSCHE / Andhra University — AP PGECET 2026 Result",
    sourceUrl: "https://cets.apsche.ap.gov.in/PGECET/",
    tags: ["AP PGECET", "M.Tech", "M.Pharm", "Results", "2026"],
  },
  // ── New: May 6, 2026 ──────────────────────────────────────────
  {
    id: "neet-ug-2026-answer-key-may-6",
    date: "2026-05-06",
    title: "NEET UG 2026 — Provisional Answer Key Was Released May 6 (Exam Now Cancelled)",
    summary: "NTA had released the NEET UG 2026 provisional answer key on May 6 at neet.nta.nic.in for codes 11, 12, 13 and 14. However, the May 3 exam has since been cancelled due to a confirmed paper leak. A re-exam (Re-NEET) is scheduled for June 21, 2026. See the May 20 update.",
    body: "The National Testing Agency (NTA) released the NEET UG 2026 provisional answer key, response sheets and question papers on Wednesday, May 6, 2026 at neet.nta.nic.in — three days after the May 3 exam.\n\n• Answer key codes released: 11, 12, 13 and 14\n• Download portal: neet.nta.nic.in (login with application number + password / DOB)\n• Objection / challenge window: Per NTA notification on the portal (fee per challenge as applicable)\n• Final answer key and result: Expected 2nd or 3rd week of June 2026\n\nExam-day snapshot (May 3, 2026):\n• Candidates registered: 22,79,743\n• Approximate attendance: 97% (~22.11 lakh appeared)\n• Centres: 551 cities in India + 14 international locations\n• Mode: Pen-and-paper, 2:00 PM – 5:00 PM\n\nReported difficulty (informal student/coaching feedback — to be verified against the final key): Overall moderate, slightly easier than NEET 2025. Physics was the toughest section; Chemistry was balanced and manageable; Biology was the most scoring overall, though Botany felt lengthy.\n\nAP/TS aspirants: NEET UG 2026 scores are required for all MBBS/BDS admissions in Andhra Pradesh (Dr. NTR UHS counselling) and Telangana (KNRUHS counselling), plus the central 15% AIQ pool (MCC) and deemed universities. AP/TS state counselling typically begins in July, after the NEET UG result.",
    category: "general",
    state: "Both",
    priority: "high",
    source: "NTA — NEET UG 2026 Provisional Answer Key Notice",
    sourceUrl: "https://neet.nta.nic.in/",
    tags: ["NEET UG", "Answer Key", "NTA", "Result", "2026"],
  },
  // ── New: May 3, 2026 ──────────────────────────────────────────
  {
    id: "neet-ug-2026-exam-conducted-may-3",
    date: "2026-05-03",
    title: "NEET UG 2026 Was Conducted on May 3 — Now Cancelled Due to Paper Leak",
    summary: "NTA conducted NEET UG 2026 on May 3 across 551 Indian cities. About 22.11 lakh candidates appeared. However, the exam has since been cancelled due to a confirmed question paper leak. A re-exam (Re-NEET) is scheduled for June 21, 2026. See the May 20 update.",
    body: "The National Testing Agency (NTA) successfully conducted NEET UG 2026, the single medical entrance exam for MBBS, BDS, BAMS, BHMS, BVSc and allied AYUSH courses, on Sunday, May 3, 2026.\n\n• Timing: 2:00 PM – 5:00 PM (pen-and-paper mode)\n• Cities: 551 in India + 14 international locations\n• Candidates registered: 22,79,743\n• Approximate attendance: 97% (~22.11 lakh appeared)\n\nAdmit cards were released on April 27 at 10 AM (a one-day postponement from the original April 26 schedule). The exam-city intimation slip had already been issued on April 12.\n\nWhat's next:\n• Provisional answer key, response sheets and question papers: Released May 6, 2026 at neet.nta.nic.in (see May 6 update)\n• Objection window: Per NTA notification\n• Final result: Expected 2nd–3rd week of June 2026\n\nFor AP/TS students: NEET UG 2026 scores are the sole criterion for MBBS/BDS admissions in Andhra Pradesh (Dr. NTR UHS counselling) and Telangana (KNRUHS counselling), as well as the all-India 15% quota (MCC) and deemed universities. State counselling notifications typically open within 1–2 weeks of the NEET UG result.",
    category: "general",
    state: "Both",
    priority: "high",
    source: "NTA — NEET UG 2026 Exam",
    sourceUrl: "https://neet.nta.nic.in/",
    tags: ["NEET UG", "NTA", "Medical", "MBBS", "2026"],
  },
  // ── New: April 26, 2026 ───────────────────────────────────────
  {
    id: "neet-ug-2026-admit-card-postponed-april-27",
    date: "2026-04-26",
    title: "NEET UG 2026 — Admit Card Was Released April 27 (May 3 Exam Now Cancelled)",
    summary: "NTA released NEET UG 2026 admit cards on April 27 at neet.nta.nic.in. The May 3 exam was conducted but has since been cancelled due to a paper leak. A re-exam is scheduled for June 21, 2026. New admit cards will be issued.",
    body: "The National Testing Agency (NTA) has postponed the release of NEET UG 2026 admit cards by one day. Originally scheduled for April 26, the hall tickets will now be available from 10:00 AM on Monday, April 27, 2026 at neet.nta.nic.in.\n\nKey points:\n• New admit card release: April 27, 2026, 10:00 AM IST\n• Download portal: neet.nta.nic.in (login with application number + password/DOB)\n• Exam date: May 3, 2026 (Sunday) — UNCHANGED\n• Timing: 2:00 PM – 5:00 PM (pen-and-paper mode)\n• Exam city intimation slip was released April 12, 2026 (separate from admit card)\n\nNTA's official announcement (via its X handle): \"NEET Admit Cards will be available to all candidates by 10 AM on Monday, 27th April 2026. Use the last Sunday before the exam for a practice test or revising concepts. Stay Calm. Keep yourself hydrated.\"\n\nWhat to do today (April 26): Use the day for revision or a full mock test. Do not download admit cards from any unofficial source. The only authoritative portal is neet.nta.nic.in.\n\nWhat to carry on exam day: Printed admit card + one valid photo ID (Aadhaar preferred). Reach the centre at least 1.5 hours before the exam — gates close 30 minutes before start. AP/TS aspirants will use NEET UG 2026 scores for MBBS/BDS counselling at Dr. NTR UHS (AP) and KNRUHS (Telangana), as well as MCC central quota and deemed universities.",
    category: "general",
    state: "Both",
    priority: "high",
    source: "NTA (NEET UG 2026 Admit Card Notice, 26.04.2026)",
    sourceUrl: "https://neet.nta.nic.in/",
    tags: ["NEET UG", "Admit Card", "Postponed", "NTA", "May 3", "2026"],
  },
  // ── New: April 21, 2026 ───────────────────────────────────────
  {
    id: "ts-ecet-2026-deadline-extended-april-23",
    date: "2026-04-21",
    title: "TS ECET 2026 — Registration Deadline Extended to April 23 (Without Late Fee)",
    summary: "Osmania University has extended the TS ECET 2026 registration deadline. Candidates can apply without late fee until April 23, 2026. Late-fee window remains open until May 12. Exam: May 15, 2026.",
    body: "Supersedes the earlier April 18 deadline: the TS (TG) ECET 2026 regular registration window has been extended to April 23, 2026.\n\n• Last date without late fee: April 23, 2026\n• Late fee applications accepted: until May 12, 2026\n• Exam date: May 15, 2026\n• Application fee: ₹900 (General), ₹500 (SC/ST/PwD)\n• Official portal: ecet.tgche.ac.in\n• Conducting body: Osmania University on behalf of TGCHE\n\nTS ECET is the lateral-entry test for diploma holders and B.Sc graduates seeking direct admission into the second year of B.Tech / B.Pharm programmes in Telangana. Payment options include debit card, credit card, and net banking. Candidates should finalise their application before April 23 to avoid late fees; documents (SSC, diploma/B.Sc marks memos, caste certificate, Aadhaar) must match the application exactly for counselling verification (expected July–August 2026).",
    category: "general",
    state: "TS",
    priority: "medium",
    source: "TGCHE / Osmania University — TS ECET 2026 Notification",
    sourceUrl: "https://ecet.tgche.ac.in/",
    tags: ["TS ECET", "TG ECET", "Lateral Entry", "Deadline Extended", "2026"],
  },
  {
    id: "jee-main-2026-session-2-results-out-april-20",
    date: "2026-04-21",
    title: "JEE Main 2026 Session 2 Results Declared — 5 Toppers from AP & Telangana, AIR 2 Jonnala Roshan (AP)",
    summary: "NTA declared JEE Main 2026 Session 2 results on April 20. 26 students scored a perfect 100 percentile — 5 are from Andhra Pradesh and Telangana. Top 2,50,182 qualify for JEE Advanced.",
    body: "The National Testing Agency (NTA) released JEE Main 2026 Session 2 results and final answer key on April 20, 2026 at jeemain.nta.nic.in.\n\nKey highlights:\n• 26 candidates scored a perfect 100 NTA percentile in Paper 1 (B.E./B.Tech)\n• Telugu states (AP + Telangana) contributed 5 of the 26 100-percentilers — the joint-highest tally\n• AIR 1: Aarush Singhal (Chandigarh)\n• AIR 2: Jonnala Roshan Mandeep Reddy (Andhra Pradesh)\n• AIR 3: Shreyas Mishra (Delhi)\n• Top female performer (All India): Mallavarapu Aasna (Telangana) with 99.9982287 percentile — no female candidate hit 100 percentile this year\n• 12 of the Session 2 toppers had also topped Session 1\n\nJEE Advanced eligibility:\n• The top 2,50,182 candidates — based on best of Session 1 + Session 2 scores — are eligible for JEE Advanced 2026\n• JEE Advanced registration opens April 23 and closes May 2, 2026\n• JEE Advanced exam: May 17, 2026 (organised by IIT Roorkee)\n\nCandidates should download their scorecards from jeemain.nta.nic.in and retain them for counselling at JoSAA/CSAB as well as for AP/TS private-university admissions (GITAM, KL University, SRM AP, VIT-AP and Vignan's accept JEE Main scores).",
    category: "general",
    state: "Both",
    priority: "high",
    source: "NTA (JEE Main 2026 Session 2 Result Notification, 20.04.2026)",
    sourceUrl: "https://jeemain.nta.nic.in/",
    tags: ["JEE Main", "Session 2", "Results", "NTA", "Toppers", "2026"],
  },
  {
    id: "tg-engineering-fee-2025-28-go-ms-06",
    date: "2026-04-21",
    title: "Telangana Fixes 2025–28 B.Tech Fee Block — ₹45,000 Floor, ₹1.83 Lakh Cap (CBIT)",
    summary: "G.O. Ms. No. 06 dated 04.03.2026 fixes B.E./B.Tech tuition fees for 160 private unaided engineering colleges in Telangana for the 2025–26 to 2027–28 block. Minimum ₹45,000/yr; CBIT tops the list at ₹1,83,000/yr.",
    body: "The Telangana Higher Education (Technical Education) Department issued G.O. Ms. No. 06 on March 4, 2026 finalising the tuition fee structure for B.E./B.Tech programmes in private unaided engineering colleges for the three-year block 2025–26 to 2027–28. The order follows recommendations of the Telangana Admission and Fee Regulatory Committee (TAFRC).\n\nFee range:\n• Minimum annual tuition fee: ₹45,000\n• Maximum annual tuition fee: ₹1,83,000 (Chaitanya Bharathi Institute of Technology — CBIT, Hyderabad)\n• 160 private unaided engineering colleges covered\n• 63 colleges saw a fee hike relative to the 2022–25 block; some institutions saw reductions\n\nScope:\n• The fee fixed is the annual tuition fee only — it does NOT include special fee or admission fee\n• Institutions must collect fees for the applicable academic year (lump sum or in instalments)\n• Applies to both convenor quota (TGCHE counselling) and management quota seats, subject to category-wise rules\n\nWhat this means for students:\n• Convenor quota fees payable during TGCHE counselling (expected July–August 2026) are now locked for the three-year block\n• The government fee-reimbursement scheme will cover the convenor-quota tuition fee for eligible candidates as per current policy\n• Management-quota and NRI fees remain college-specific but are capped by the block ceiling\n\nTeluguColleges will update the per-college fee pages (/colleges/[slug]/fees) to reflect the 2025–28 block figures over the coming weeks as the TAFRC list is tabulated.",
    category: "fees",
    state: "TS",
    priority: "high",
    source: "Government of Telangana — Higher Education (TE) Dept., G.O. Ms. No. 06 dated 04.03.2026 / TAFRC",
    sourceUrl: "https://tafrc.telangana.gov.in/",
    tags: ["Telangana", "Engineering Fees", "TAFRC", "B.Tech", "2025-28", "CBIT", "Fee Block"],
  },
  {
    id: "neet-ug-2026-exam-may-3-admit-card-expected",
    date: "2026-04-21",
    title: "NEET UG 2026 — Original Schedule (May 3 Exam Now Cancelled; Re-Exam June 21)",
    summary: "NEET UG 2026 was originally scheduled for May 3. The exam was conducted but has since been cancelled due to a confirmed paper leak. Re-NEET 2026 is now scheduled for June 21, 2026. See the May 20 update for full details.",
    body: "The National Testing Agency (NTA) has confirmed key details for NEET UG 2026, the single medical/dental/AYUSH entrance exam for MBBS, BDS, BAMS, BHMS, B.V.Sc and allied courses.\n\n• Exam date: May 3, 2026 (Sunday)\n• Timing: 2:00 PM – 5:00 PM (pen-and-paper mode)\n• Exam city intimation slip: Released April 12, 2026\n• Admit card: Originally expected April 26, 2026 — postponed to April 27, 2026 at 10:00 AM (see April 26 update)\n• Download portal: neet.nta.nic.in\n\nWhat AP/TS aspirants should do now:\n• Check the city intimation slip on neet.nta.nic.in and plan travel/accommodation early\n• Carry the printed admit card + one valid photo ID (Aadhaar preferred) to the exam centre\n• Reach the centre at least 1.5 hours before the exam; centres close gate 30 minutes before start\n• NEET UG 2026 scores are required for all MBBS/BDS admissions in AP (Dr. NTR UHS counselling) and Telangana (KNRUHS counselling), as well as central quota (MCC) and deemed universities\n\nAP/TS medical counselling is expected to start after NEET UG results, typically in July 2026.",
    category: "general",
    state: "Both",
    priority: "high",
    source: "NTA (NEET UG 2026 Schedule)",
    sourceUrl: "https://neet.nta.nic.in/",
    tags: ["NEET UG", "Medical", "MBBS", "NTA", "Admit Card", "2026"],
  },
  {
    id: "jee-advanced-2026-registration-update-april-21",
    date: "2026-04-21",
    title: "Correction — JEE Advanced 2026 Organised by IIT Roorkee (Not IIT Dhanbad), Result June 1",
    summary: "Clarifying earlier reports: JEE Advanced 2026 is organised by IIT Roorkee. Registration runs April 23 – May 2; admit card May 11; exam May 17; result June 1, 2026.",
    body: "Confirmed schedule from the official JEE Advanced 2026 notification (jeeadv.ac.in):\n\n• Organising institute: IIT Roorkee (rotating zonal coordinator for 2026)\n• Registration opens (Indian nationals): April 23, 2026 at 10:00 IST\n• Registration closes: May 2, 2026 at 23:59 IST\n• Last date for fee payment: May 4, 2026\n• Admit card download: May 11–17, 2026\n• Exam: May 17, 2026 — Paper 1 (09:00–12:00), Paper 2 (14:30–17:30)\n• Result: June 1, 2026\n• Foreign/OCI/PIO registration opens: April 6, 2026\n\nEligibility: top 2,50,182 candidates from JEE Main 2026 (combined Session 1 + Session 2 best scores), subject to category and age rules. Architecture Aptitude Test (AAT) registration opens after the JEE Advanced result.\n\nThis notice corrects earlier coverage that referenced IIT Dhanbad and a June 8 result date — the authoritative source is the JEE (Advanced) 2026 portal.",
    category: "general",
    state: "Both",
    priority: "medium",
    source: "JEE (Advanced) 2026 — IIT Roorkee",
    sourceUrl: "https://jeeadv.ac.in/",
    tags: ["JEE Advanced", "IIT Roorkee", "Registration", "Correction", "2026"],
  },
  // ── New: April 12, 2026 ───────────────────────────────────────
  {
    id: "jee-main-2026-session-2-results-expected",
    date: "2026-04-12",
    title: "JEE Main 2026 Session 2 — Results Expected by April 20",
    summary: "JEE Main 2026 Session 2 exam concluded on April 9. Answer key released April 11. Final results and All India Ranks expected by April 20.",
    body: "JEE Main 2026 Session 2 has been completed successfully.\n\n• Exam conducted: April 2–9, 2026 (CBT mode)\n• Provisional answer key: Released April 11 at jeemain.nta.nic.in\n• Challenge window: Open until April 13, 2026\n• Final result & AIR: Expected by April 20, 2026\n\nSession 2 results will include JEE Advanced 2026 qualification cutoffs and final All India Ranks. Candidates who appeared in both sessions will be awarded the better of the two NTA scores.\n\nJEE Advanced 2026 registration opens April 23 (exam May 17). Top 2.5 lakh JEE Main qualifiers are eligible.\n\nFor AP/TS students — JEE Main scores are accepted by GITAM, KL University, SRM AP, and Vignan's for direct admission without separate entrance exams.",
    category: "general",
    state: "Both",
    priority: "high",
    source: "NTA",
    sourceUrl: "https://jeemain.nta.nic.in/",
    tags: ["JEE Main", "Session 2", "Results", "NTA", "JEE Advanced", "2026"],
  },
  {
    id: "jee-advanced-2026-registration-april-23",
    date: "2026-04-12",
    title: "JEE Advanced 2026 — Registration Opens April 23, Exam on May 17",
    summary: "JEE Advanced 2026 registration opens April 23 and closes May 2. Exam scheduled for May 17, organised by IIT Roorkee. Top 2.5 lakh JEE Main qualifiers eligible.",
    body: "JEE Advanced 2026, the gateway to all 23 IITs, has confirmed its schedule.\n\n• Registration opens: April 23, 2026 (10:00 IST)\n• Registration closes: May 2, 2026 (23:59 IST)\n• Last date for fee payment: May 4, 2026\n• Admit card download: May 11, 2026\n• Exam date: May 17, 2026 (Paper 1: 9 AM–12 PM, Paper 2: 2:30 PM–5:30 PM)\n• Organising institute: IIT Roorkee\n• Result: June 1, 2026\n\nEligibility: Top 2,50,000 candidates from JEE Main 2026 (across all categories). Candidates must have been born on or after October 1, 2001 (relaxation for reserved categories).\n\nIIT Hyderabad remains a top choice for AP/TS students. Architecture Aptitude Test (AAT) registration opens after JEE Advanced results.",
    category: "general",
    state: "Both",
    priority: "high",
    source: "JEE Advanced 2026",
    sourceUrl: "https://jeeadv.ac.in/",
    tags: ["JEE Advanced", "IIT", "Registration", "2026"],
  },
  {
    id: "tg-eapcet-2026-admit-cards-april",
    date: "2026-04-12",
    title: "TG EAPCET 2026 — Admit Cards: Agriculture April 23, Engineering April 27",
    summary: "TG EAPCET 2026 admit cards will be released on April 23 (Agriculture/Pharmacy) and April 27 (Engineering). Correction window has closed.",
    body: "TG EAPCET 2026 admit card schedule has been confirmed.\n\n• Agriculture/Pharmacy admit card: April 23, 2026\n• Engineering admit card: April 27, 2026\n• Download at: eapcet.tgche.ac.in\n• Application correction window: Closed (ended April 8)\n\nExam schedule:\n• Agriculture/Pharmacy: May 4–5, 2026\n• Engineering: May 9–11, 2026\n• Shifts: Morning (9 AM–12 PM) and Afternoon (3 PM–6 PM)\n• 160 MCQs for 160 marks, no negative marking\n\nLate registration is still open with progressive late fees (₹1,000 until April 25, ₹2,000 until April 28, ₹10,000 until May 2). Download admit cards using your registration number and date of birth.",
    category: "eapcet",
    state: "TS",
    priority: "high",
    source: "TGCHE / JNTU Hyderabad",
    sourceUrl: "https://eapcet.tgche.ac.in/",
    tags: ["TG EAPCET", "Admit Card", "2026"],
  },
  {
    id: "ts-ecet-2026-last-date-april-18",
    date: "2026-04-12",
    title: "TS ECET 2026 — Earlier Deadline Was April 18 (Superseded)",
    summary: "As originally notified, TS ECET 2026 had a regular registration deadline of April 18. This window was later extended — see the April 21 update.",
    body: "This item is retained as a historical reference. As originally notified in early April:\n\n• Regular deadline (no late fee): April 18, 2026\n• Exam date: May 15, 2026\n• Eligibility: Diploma holders and B.Sc graduates seeking lateral entry into B.Tech/B.Pharm second year\n• Official website: ecet.tgche.ac.in\n\nUpdate (April 21, 2026): Osmania University — which is conducting TS ECET 2026 on behalf of TGCHE — extended the registration deadline to April 23, 2026 without late fee. A subsequent late-fee window remains open until May 12, 2026. See the April 21 news item for the current timeline.\n\nCandidates should verify all timelines on the official portal before applying.",
    category: "general",
    state: "TS",
    priority: "low",
    source: "TGCHE / Osmania University",
    sourceUrl: "https://ecet.tgche.ac.in/",
    tags: ["TS ECET", "Lateral Entry", "2026", "Diploma", "Superseded"],
  },
  {
    id: "ap-icet-2026-admit-card-released",
    date: "2026-04-12",
    title: "AP ICET 2026 — Admit Card Released, Exam on May 2",
    summary: "AP ICET 2026 admit cards are now available for download. The MBA/MCA entrance exam is scheduled for May 2, 2026.",
    body: "AP ICET 2026 admit cards have been released for download.\n\n• Admit card available at: cets.apsche.ap.gov.in/ICET\n• Exam date: May 2, 2026\n• Download using: Registration number + date of birth\n• Late fee registration: Closed (final deadline was April 5)\n\nAP ICET is the entrance test for MBA and MCA admissions in all AP-affiliated universities and colleges. Candidates should download and print their admit cards well in advance.\n\nEnsure you carry a valid photo ID along with the admit card to the exam centre. Check the venue details on your admit card and plan your travel accordingly.",
    category: "general",
    state: "AP",
    priority: "medium",
    source: "APSCHE",
    sourceUrl: "https://cets.apsche.ap.gov.in/ICET/",
    tags: ["AP ICET", "MBA", "MCA", "Admit Card", "2026"],
  },
  {
    id: "ap-pgecet-2026-exam-april-28-30",
    date: "2026-04-12",
    title: "AP PGECET 2026 — Exam on April 28–30, Admit Cards Released April 15",
    summary: "AP PGECET 2026 exam is scheduled for April 28–30, 2026 in two daily sessions. Admit cards were released on April 15, 2026 at cets.apsche.ap.gov.in for M.Tech, M.Pharm, M.Arch and Pharm.D (PB) aspirants.",
    body: "AP Post Graduate Engineering Common Entrance Test (AP PGECET) 2026 is just days away.\n\n• Exam dates: April 28, 29 & 30, 2026 (CBT, two sessions/day)\n• For admissions to: M.E/M.Tech, M.Pharm, M.Arch, Pharm.D (PB)\n• Conducting university: Andhra University, Visakhapatnam (on behalf of APSCHE)\n• Admit card: Released April 15, 2026 — download at cets.apsche.ap.gov.in using registration number, qualifying-exam hall ticket number and date of birth\n• Result: May 14, 2026 (expected)\n\nThis exam is for B.Tech/B.E. graduates seeking postgraduate engineering education in Andhra Pradesh. Qualifying AP PGECET along with a valid GATE score improves chances during counselling.\n\nCounselling is expected in July–August 2026 along with AP EAPCET counselling. Carry a printed admit card and a valid photo ID (Aadhaar preferred) to the exam centre.",
    category: "general",
    state: "AP",
    priority: "low",
    source: "APSCHE",
    sourceUrl: "https://cets.apsche.ap.gov.in/",
    tags: ["AP PGECET", "M.Tech", "M.Pharm", "2026"],
  },
  // ── Updated: March 26, 2026 ────────────────────────────────────
  {
    id: "ap-eapcet-2026-correction-window-open",
    date: "2026-03-26",
    title: "AP EAPCET 2026 — Application Correction Window Closed, Admit Cards April 28",
    summary: "The AP EAPCET 2026 correction window (March 26–28) has closed. Next milestone: admit card download from April 28.",
    body: "The AP EAPCET 2026 application form correction window has closed.\n\n• Correction window: March 26–28, 2026 (closed)\n• Status: All corrections finalized\n\nUpcoming key dates:\n• Admit card download: April 28, 2026 onwards at cets.apsche.ap.gov.in\n• Engineering exam: May 12, 13, 14, 15 & 18, 2026\n• Agriculture/Pharmacy exam: May 19 & 20, 2026\n• Result: June 1, 2026\n\nCandidates should now focus on exam preparation. Admit cards will be downloadable using registration number or payment reference ID, qualifying exam hall ticket number, and date of birth.",
    category: "eapcet",
    state: "AP",
    priority: "high",
    source: "APSCHE",
    sourceUrl: "https://cets.apsche.ap.gov.in/EAPCET/",
    tags: ["AP EAPCET", "Correction Window", "Admit Card", "2026"],
  },
  {
    id: "tg-eapcet-2026-registration-deadline-april-4",
    date: "2026-03-26",
    title: "TG EAPCET 2026 — Registration Closed, Late Fee Window Still Open",
    summary: "TG EAPCET 2026 regular registration (April 4) has closed. Late fee applications still accepted until May 2. Correction window ended April 8.",
    body: "TG EAPCET (formerly TS EAMCET) 2026 registration update.\n\n• Regular deadline (April 4): Closed\n• Form correction window (April 6–8): Closed\n• Late fee registration: Still open (₹1,000 until April 25, ₹2,000 until April 28, ₹10,000 until May 2)\n• Official website: eapcet.tgche.ac.in\n\nExam schedule:\n• Agriculture/Pharmacy: May 4–5, 2026\n• Engineering: May 9–11, 2026\n• Admit cards: Agriculture April 23 | Engineering April 27\n\nThe exam will have 160 MCQs for 160 marks with no negative marking. Two shifts per day — 9 AM to 12 PM and 3 PM to 6 PM.",
    category: "eapcet",
    state: "TS",
    priority: "high",
    source: "TGCHE / JNTU Hyderabad",
    sourceUrl: "https://eapcet.tgche.ac.in/",
    tags: ["TG EAPCET", "TS EAMCET", "Registration", "Late Fee", "2026"],
  },
  {
    id: "jee-main-2026-session-2-april",
    date: "2026-03-26",
    title: "JEE Main 2026 Session 2 — Exam Completed, Results Expected April 20",
    summary: "JEE Main 2026 Session 2 was conducted April 2–9. Answer key released April 11. Results and AIR expected by April 20.",
    body: "JEE Main 2026 Session 2 has been completed.\n\n• Exam conducted: April 2–9, 2026 (CBT mode)\n• Answer key: Released April 11 at jeemain.nta.nic.in\n• Result: Expected by April 20, 2026\n\nSession 2 results will include JEE Advanced 2026 qualification cutoffs and All India Ranks. Candidates who appeared in both sessions will be awarded the better of the two NTA scores.\n\nJEE Advanced 2026: Registration opens April 23, exam on May 17.\n\nFor students targeting AP/TS private and deemed universities — JEE Main scores are accepted by GITAM (GAT waiver), KL University, SRM AP, and Vignan's (V-SAT waiver) for direct admission.",
    category: "general",
    state: "Both",
    priority: "high",
    source: "NTA",
    sourceUrl: "https://jeemain.nta.nic.in/",
    tags: ["JEE Main", "Session 2", "NTA", "Results", "2026"],
  },
  {
    id: "ap-icet-2026-late-fee-deadline-march-26",
    date: "2026-03-26",
    title: "AP ICET 2026 — Registration Closed, Admit Card Now Available",
    summary: "AP ICET 2026 registration has closed (final deadline April 5). Admit cards are now available for download. Exam on May 2.",
    body: "AP ICET 2026 (for MBA/MCA admissions) registration is now closed.\n\n• Regular deadline: Closed (March 23)\n• Final late fee deadline (₹10,000): Closed (April 5)\n• Admit card: Now available at cets.apsche.ap.gov.in/ICET\n• Exam date: May 2, 2026\n\nCandidates who registered should download their admit cards immediately. Carry a valid photo ID along with the printed admit card to the exam centre.\n\nAP ICET is conducted by APSCHE for admission to MBA and MCA programs in AP-affiliated universities and colleges.",
    category: "general",
    state: "AP",
    priority: "medium",
    source: "APSCHE",
    sourceUrl: "https://cets.apsche.ap.gov.in/ICET/",
    tags: ["AP ICET", "MBA", "MCA", "Admit Card", "2026"],
  },
  // ── Updated: March 17, 2026 ────────────────────────────────────
  {
    id: "ap-eapcet-2026-result-admit-card-dates",
    date: "2026-03-17",
    title: "AP EAPCET 2026 — Result on June 1, Admit Card Available April 28",
    summary: "JNTU Kakinada has confirmed that AP EAPCET 2026 results will be declared on June 1, 2026. Admit cards will be available for download from April 28.",
    body: "Key upcoming dates for AP EAPCET 2026 candidates:\n\n• Application form correction window: March 26–28, 2026 (closed)\n• Admit card download: April 28, 2026 onwards at cets.apsche.ap.gov.in\n• Engineering exam: May 12, 13, 14, 15 & 18, 2026\n• Agriculture/Pharmacy exam: May 19 & 20, 2026\n• Result declaration: June 1, 2026\n\nCandidates can download their hall tickets using registration number or payment reference ID, qualifying exam hall ticket number, and date of birth. Keep the admit card safe — it is required throughout the admission process.\n\nNote: AP EAPCET 2026 application fees have been revised to ₹800 (General), ₹750 (BC), ₹700 (SC/ST) — a ₹200 increase across all categories.",
    category: "eapcet",
    state: "AP",
    priority: "high",
    source: "APSCHE Official Notification",
    sourceUrl: "https://cets.apsche.ap.gov.in/EAPCET/",
    tags: ["AP EAPCET", "Result Date", "Admit Card", "2026"],
  },
  {
    id: "iiit-hyderabad-ugee-2026-registration",
    date: "2026-03-17",
    title: "IIIT Hyderabad UGEE 2026 — Registration Closed, Exam on May 2",
    summary: "IIIT Hyderabad UGEE 2026 registration closed March 31. The entrance exam will be held on May 2.",
    body: "The International Institute of Information Technology, Hyderabad (IIIT-H) UGEE 2026 registration has closed.\n\n• Registration: Closed (deadline was March 31, 2026)\n• Exam date: May 2, 2026 (9:00 AM – 12:00 Noon)\n• Interview dates: June 4–6, 2026 (on campus)\n\nIIIT Hyderabad is one of the top CS/IT institutions in India. Admission is through UGEE scores + JEE Mains marks + interview. Registered candidates should prepare for the upcoming exam.\n\nCheck ugadmissions.iiit.ac.in for admit card updates.",
    category: "general",
    state: "TS",
    priority: "medium",
    source: "IIIT Hyderabad",
    sourceUrl: "https://ugadmissions.iiit.ac.in/ugee/",
    tags: ["IIIT Hyderabad", "UGEE", "Exam", "2026"],
  },
  {
    id: "gitam-gat-2026-march-phase",
    date: "2026-03-17",
    title: "GITAM GAT 2026 — March Phase Completed, Further Phases Available",
    summary: "GITAM GAT 2026 March phase exam (March 29) has been completed. Further admission phases are available throughout 2026.",
    body: "GITAM (Gandhi Institute of Technology and Management) GAT 2026 March phase has been completed.\n\n• March phase exam: Completed (March 29, 2026)\n• Results: Announced on the day of the exam\n• Campuses: Visakhapatnam (AP), Hyderabad (TS), Bengaluru\n\nGITAM conducts GAT in multiple phases throughout the admission season. Students who missed the March phase can register for upcoming phases at apply.gitam.edu.\n\nGITAM is a Deemed University with NAAC A++ accreditation, offering B.Tech programs across multiple branches. JEE Main score holders may be eligible for GAT waiver — check the GITAM admissions portal for details.",
    category: "general",
    state: "Both",
    priority: "low",
    source: "GITAM University",
    sourceUrl: "https://apply.gitam.edu/",
    tags: ["GITAM", "GAT", "Admission", "2026", "Visakhapatnam", "Hyderabad"],
  },
  {
    id: "bitsat-2026-registration-deadline",
    date: "2026-03-17",
    title: "BITSAT 2026 — Session 1 Completed, Session 2 Registration Open",
    summary: "BITSAT 2026 Session 1 (April 15–16) has been completed. Session 2 registration is open until May 2, exam on May 24–26.",
    body: "BITS Pilani BITSAT 2026 Session 1 has been completed.\n\n• Session 1 exam: Completed (April 15–16, 2026)\n• Admit cards for Session 1: Were released April 10\n• Session 2 registration: Open until May 2, 2026\n• Session 2 exam: May 24–26, 2026\n\nMajor update: Starting with the 2026–27 academic year, BITS Pilani has introduced tuition-blind admissions for the top 500 BITSAT rank holders, offering a four-year scholarship covering full tuition fees.\n\nStudents who missed Session 1 can still register for Session 2. BITS Pilani Hyderabad campus is a top choice for AP and TS engineering aspirants. Apply at admissions.bits-pilani.ac.in.",
    category: "general",
    state: "Both",
    priority: "medium",
    source: "BITS Pilani Admissions",
    sourceUrl: "https://admissions.bits-pilani.ac.in/",
    tags: ["BITSAT", "BITS Pilani", "Session 2", "Registration", "Scholarship", "2026"],
  },
  {
    id: "viteee-srmjeee-2026-deadlines",
    date: "2026-03-17",
    title: "VITEEE 2026 Exam Underway, SRMJEEE Phase 1 Revised to April 24–29",
    summary: "VITEEE 2026 registration closed April 12. Exam runs April 28–May 3. SRMJEEE Phase 1 revised to April 24–29.",
    body: "Updates on two major private university entrance exams:\n\nVITEEE 2026 (VIT Vellore, Chennai, AP-Amaravati, Bhopal):\n• Registration: Closed (extended deadline was April 12, 2026)\n• Exam dates: April 28 – May 3, 2026 (slot-based online)\n• VIT-AP (Amaravati) campus is relevant for AP students\n• Slot booking in progress at viteee.vit.ac.in\n\nSRMJEEE 2026 (SRM University):\n• Phase 1 exam: Revised to April 24–29, 2026 (remote proctored, home-based)\n• Phase 2: June 10–15 | Phase 3: July 4–5\n• No negative marking. Application fee: ₹1,400 per phase\n• Apply at applications.srmist.edu.in/btech\n\nBoth VIT and SRM are popular choices for AP/TS students seeking private university B.Tech admissions.",
    category: "general",
    state: "Both",
    priority: "medium",
    source: "VIT / SRM Official",
    sourceUrl: "https://viteee.vit.ac.in/",
    tags: ["VITEEE", "SRMJEEE", "VIT", "SRM", "Exam", "2026"],
  },

  // ── EAPCET 2026 ──────────────────────────────────────────────
  {
    id: "ap-eapcet-2026-deadline",
    date: "2026-03-17",
    title: "AP EAPCET 2026 — Last Date Extended Again to March 24 (No Late Fee)",
    summary: "APSCHE has extended the AP EAPCET 2026 registration deadline once more — apply without late fee by March 24, 2026.",
    body: "The Andhra Pradesh State Council of Higher Education (APSCHE) has extended the last date for AP EAPCET 2026 registration without late fee to March 24, 2026. This is the second extension (previously March 17).\n\nRevised late fee schedule:\n• ₹1,000 late fee: by March 28\n• ₹2,000 late fee: by April 1\n• ₹4,000 late fee: by April 6\n• ₹10,000 late fee: by April 10\n• Correction window: April 11–13\n\nApplication fee: ₹800 (General), ₹750 (BC), ₹700 (SC/ST). The exam is conducted by JNTU Kakinada on behalf of APSCHE. Apply at cets.apsche.ap.gov.in/EAPCET.",
    category: "eapcet",
    state: "AP",
    priority: "high",
    source: "APSCHE Official Notification",
    sourceUrl: "https://cets.apsche.ap.gov.in/EAPCET/",
    tags: ["AP EAPCET", "Registration", "Deadline", "2026"],
  },
  {
    id: "ap-eapcet-2026-exam-dates",
    date: "2026-02-04",
    title: "AP EAPCET 2026 Exam Dates Announced — Engineering: May 12–18",
    summary: "APSCHE has released the full AP EAPCET 2026 schedule. Engineering exam on May 12, 13, 14, 15 & 18. Agriculture/Pharmacy on May 19 & 20.",
    body: "The AP-CETs 2026 notification was issued on February 3, 2026 by the Secretary of APSCHE, Guntur. AP EAPCET (APEAPCET) 2026 for Engineering will be conducted by JNTU Kakinada on May 12, 13, 14, 15, and 18, 2026. The Agriculture & Pharmacy stream exam (APECET) will be conducted by JNTU Anantapur on April 23, 2026.\n\nAll AP CETs 2026 will be conducted through Computer Based Test (CBT) mode. Registration opened February 4, 2026.\n\nOther AP CETs: APICET (May 2), APPGECET (April 28–30), APLAWCET (May 4), APEDCET (May 4), APPGCET (May 8–11), APPECET (June 3).",
    category: "eapcet",
    state: "AP",
    priority: "high",
    source: "APSCHE Official Notification (03.02.2026)",
    sourceUrl: "https://cets.apsche.ap.gov.in/EAPCET/",
    tags: ["AP EAPCET", "Exam Dates", "2026", "AP CETs"],
  },
  {
    id: "ts-eapcet-2026-registration",
    date: "2026-02-19",
    title: "TG EAPCET 2026 Registration Open — Apply by April 4 Without Late Fee",
    summary: "Telangana EAPCET 2026 application forms are live. Last date without late fee is April 4, 2026. Exam: May 4–11.",
    body: "JNTU Hyderabad, on behalf of TGCHE, has opened online registration for TG EAPCET 2026 from February 19, 2026. Candidates can apply without late fee until April 4, 2026.\n\nLate fee schedule: ₹250 (by April 10), ₹500 (by April 15), ₹2,500 (by April 20), ₹5,000 (by April 24), ₹10,000 (by May 2).\n\nApplication fee: ₹900 (General, single stream), ₹1,800 (both streams), ₹500/₹1,000 (SC/ST/PH).\n\nExam dates — Agriculture & Pharmacy: May 4–5; Engineering: May 9–11 (two shifts per day: 9 AM–12 PM and 3–6 PM).\n\nApply at eapcet.tgche.ac.in.",
    category: "eapcet",
    state: "TS",
    priority: "high",
    source: "TGCHE / JNTUH Official Notification",
    sourceUrl: "https://eapcet.tgche.ac.in/",
    tags: ["TS EAPCET", "TG EAPCET", "Registration", "2026"],
  },
  {
    id: "ts-eapcet-2026-marks-vs-rank",
    date: "2026-02-19",
    title: "TG EAPCET 2026 — Marks vs Rank Band Reference (2024 & 2025 Data)",
    summary: "Official normalization marks vs rank band data released for TG EAPCET 2026 based on 2024 and 2025 performance.",
    body: "The TG EAPCET 2026 convener has published marks-vs-rank reference tables based on TG EAPCET 2024 and 2025 data.\n\nEngineering (2025): 80+ marks → below rank 2,613 | 75+ → 2,614–3,995 | 70+ → 3,996–6,104 | 65+ → 6,105–9,226 | 60+ → 9,227–14,418 | 55+ → 14,419–24,028 | 50+ → 24,029–44,121 | 45+ → 44,122–82,343 | 40+ → 82,344–1,35,462.\n\nAgriculture & Pharmacy (2025): 80+ → below 2,726 | 70+ → 4,629–7,182 | 60+ → 10,537–15,011 | 50+ → 21,745–32,151 | 40+ → 46,573–61,764.\n\nNote: These are based on normalized marks out of 160.",
    category: "eapcet",
    state: "TS",
    priority: "medium",
    source: "TG EAPCET 2026 Convener",
    sourceUrl: "https://eapcet.tgche.ac.in/",
    tags: ["TS EAPCET", "Marks vs Rank", "Reference", "2026"],
  },

  // ── Counselling & Admissions ──────────────────────────────────
  {
    id: "ap-eapcet-2026-counselling-preview",
    date: "2026-03-14",
    title: "AP EAPCET 2026 Counselling Expected July 2026 — What to Expect",
    summary: "AP EAPCET 2026 counselling is expected to begin in the first week of July 2026 with 2 rounds of web counselling.",
    body: "Based on previous years' schedules, AP EAPCET 2026 counselling is expected to start in the 1st week of July 2026. The process will include:\n\n1. Online registration and slot booking\n2. Certificate verification at designated Help Line Centers\n3. Web options entry (choosing colleges and branches)\n4. Seat allotment (2 rounds + spot round)\n5. Reporting to allotted college\n\nCounselling registration fee: ₹1,200 (OC/BC), ₹600 (SC/ST).\n\nCategory-A (Convener Quota): ~70% of seats filled via APSCHE counselling.\nCategory-B (Management Quota): ~30% — fees regulated by APHERMC.",
    category: "counselling",
    state: "AP",
    priority: "low",
    source: "APSCHE",
    sourceUrl: "https://cets.apsche.ap.gov.in/EAPCET/",
    tags: ["Counselling", "AP EAPCET", "2026", "Admissions"],
  },
  {
    id: "ts-eapcet-2026-counselling-preview",
    date: "2026-03-14",
    title: "TS EAPCET 2026 Counselling Expected July–August 2026",
    summary: "Telangana EAPCET counselling typically runs July–August with 3 rounds + 1 special round.",
    body: "TS EAPCET 2026 counselling is expected to begin in July 2026, running through August. Based on previous years:\n\n• 3 regular rounds + 1 special round\n• Convener quota: 70% of seats filled via TSCHE web counselling\n• Minimum qualifying marks: 25% (40 out of 160)\n• Registration fee: ₹1,200 (unreserved), ₹600 (reserved categories)\n\nCounselling will be conducted through the TSCHE website. Candidates need to register, verify documents, enter web options, and report to allotted college within the specified timeline.\n\nFee regulation: TS AFRC (block period system, currently 2025–28 per G.O. Ms. No. 06).",
    category: "counselling",
    state: "TS",
    priority: "low",
    source: "TSCHE",
    sourceUrl: "https://eapcet.tgche.ac.in/",
    tags: ["Counselling", "TS EAPCET", "2026", "Admissions"],
  },

  // ── Other CETs ────────────────────────────────────────────────
  {
    id: "tg-pgecet-2026",
    date: "2026-02-27",
    title: "TG PGECET 2026 Applications Open — M.Tech, M.Pharm, M.Arch Admissions",
    summary: "Applications for Telangana PGECET 2026 (M.E/M.Tech, M.Pharm, M.Arch, Pharm.D) are open from February 27 for AY 2026–27.",
    body: "The Telangana Post Graduate Engineering Common Entrance Test (TG PGECET) 2026 applications have opened from February 27, 2026, for admissions into M.E/M.Tech, M.Pharm, M.Arch, and Pharm.D courses for the 2026–27 academic year.\n\nThis is relevant for students who have completed their B.Tech/B.E. and are looking to pursue higher education in Telangana.",
    category: "general",
    state: "TS",
    priority: "low",
    source: "TGCHE",
    sourceUrl: "https://eapcet.tgche.ac.in/",
    tags: ["PGECET", "M.Tech", "Telangana", "2026"],
  },
  {
    id: "ap-ecet-2026",
    date: "2026-03-14",
    title: "AP ECET 2026 — Lateral Entry Engineering Applications Open",
    summary: "AP ECET 2026 applications are open for lateral entry admissions into engineering and pharmacy programs.",
    body: "Applications for AP ECET (Engineering Common Entrance Test) 2026 are open for diploma holders and B.Sc degree holders seeking lateral entry into B.Tech/B.Pharm second year. This is conducted by Acharya Nagarjuna University on behalf of APSCHE.\n\nPhysical Efficiency and Games Skill Test commences on June 3, 2026. Registration started February 13, 2026.",
    category: "general",
    state: "AP",
    priority: "low",
    source: "APSCHE",
    sourceUrl: "https://cets.apsche.ap.gov.in/",
    tags: ["AP ECET", "Lateral Entry", "2026"],
  },

  // ── NAAC / NIRF ───────────────────────────────────────────────
  {
    id: "nirf-naac-2026-status",
    date: "2026-03-14",
    title: "NIRF 2026 Rankings & NAAC Updates — Not Yet Released",
    summary: "NIRF 2026 rankings are expected later in 2026. No new NAAC accreditations for AP/TS colleges announced yet.",
    body: "As of March 14, 2026:\n\n• NIRF 2026 rankings have NOT been released yet. Expected mid-to-late 2026.\n• NAAC A++ updated list for 2026 is expected around August 2026 — no new cycle completions announced.\n• No new NAAC accreditations specifically for AP or TS engineering colleges were found.\n• Notable existing: Andhra University holds NAAC A++ grade. NALSAR (Hyderabad) holds NAAC A++ (CGPA 3.52).\n\nTeluguColleges.com NAAC data reflects the latest available grades.",
    category: "naac-nirf",
    state: "Both",
    priority: "low",
    source: "NAAC / NIRF",
    tags: ["NIRF", "NAAC", "Rankings", "2026"],
  },
];

// Helper to get the latest N news items
export function getLatestNews(n: number = 10): NewsItem[] {
  return [...NEWS_ITEMS].sort((a, b) => b.date.localeCompare(a.date)).slice(0, n);
}

// Helper to filter by state
export function getNewsByState(state: "AP" | "TS" | "Both"): NewsItem[] {
  return NEWS_ITEMS.filter(n => n.state === state || n.state === "Both")
    .sort((a, b) => b.date.localeCompare(a.date));
}

// Helper to filter by category
export function getNewsByCategory(category: NewsItem["category"]): NewsItem[] {
  return NEWS_ITEMS.filter(n => n.category === category)
    .sort((a, b) => b.date.localeCompare(a.date));
}

// Category metadata
export const NEWS_CATEGORIES: { key: NewsItem["category"]; label: string; color: string; bgColor: string }[] = [
  { key: "eapcet", label: "EAPCET 2026", color: "text-blue-700", bgColor: "bg-blue-50" },
  { key: "fees", label: "Fees", color: "text-emerald-700", bgColor: "bg-emerald-50" },
  { key: "counselling", label: "Counselling", color: "text-purple-700", bgColor: "bg-purple-50" },
  { key: "naac-nirf", label: "NAAC / NIRF", color: "text-amber-700", bgColor: "bg-amber-50" },
  { key: "general", label: "General", color: "text-gray-700", bgColor: "bg-gray-100" },
];
