var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/colleges/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__7b0a720b._.js")
R.c("server/chunks/ssr/0f9d8_next_dist_794c7656._.js")
R.c("server/chunks/ssr/mnt_telugucolleges_e0b09721._.js")
R.c("server/chunks/ssr/[root-of-the-server]__882eef9c._.js")
R.c("server/chunks/ssr/[root-of-the-server]__4d4c6308._.js")
R.c("server/chunks/ssr/0f9d8_next_dist_ce9372ae._.js")
R.c("server/chunks/ssr/0f9d8_next_dist_client_components_builtin_global-error_27334d3b.js")
R.c("server/chunks/ssr/mnt_telugucolleges_5b5602f3._.js")
R.c("server/chunks/ssr/0f9d8_next_dist_client_components_9a1fb573._.js")
R.c("server/chunks/ssr/0f9d8_next_dist_client_components_builtin_forbidden_d0d8d30c.js")
R.c("server/chunks/ssr/0f9d8_next_dist_client_components_builtin_unauthorized_70f63c12.js")
R.c("server/chunks/ssr/mnt_telugucolleges__next-internal_server_app_colleges_page_actions_74cacd8c.js")
R.m(84145)
module.exports=R.m(84145).exports
