var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/programs/[slug]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__308b4944._.js")
R.c("server/chunks/ssr/mnt_telugucolleges_121ab571._.js")
R.c("server/chunks/ssr/mnt_telugucolleges_src_lib_program-data_ts_977ffd1a._.js")
R.c("server/chunks/ssr/0f9d8_next_dist_794c7656._.js")
R.c("server/chunks/ssr/0f9d8_next_dist_48afbe1b._.js")
R.c("server/chunks/ssr/mnt_telugucolleges_src_lib_colleges_ts_3fd8fc44._.js")
R.c("server/chunks/ssr/[root-of-the-server]__882eef9c._.js")
R.c("server/chunks/ssr/[root-of-the-server]__4d4c6308._.js")
R.c("server/chunks/ssr/0f9d8_next_dist_ce9372ae._.js")
R.c("server/chunks/ssr/0f9d8_next_dist_client_components_builtin_global-error_27334d3b.js")
R.c("server/chunks/ssr/mnt_telugucolleges_5b5602f3._.js")
R.c("server/chunks/ssr/0f9d8_next_dist_client_components_9a1fb573._.js")
R.c("server/chunks/ssr/0f9d8_next_dist_client_components_builtin_forbidden_d0d8d30c.js")
R.c("server/chunks/ssr/0f9d8_next_dist_client_components_builtin_unauthorized_70f63c12.js")
R.c("server/chunks/ssr/372cd_telugucolleges__next-internal_server_app_programs_[slug]_page_actions_402103bb.js")
R.m(99831)
module.exports=R.m(99831).exports
