var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/programs/[slug]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__bfb7c3f3._.js")
R.c("server/chunks/ssr/_7d601e4c._.js")
R.c("server/chunks/ssr/src_lib_program-data_ts_27341464._.js")
R.c("server/chunks/ssr/node_modules_next_dist_4b63a0e1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_023b6025._.js")
R.c("server/chunks/ssr/src_lib_colleges_ts_0585557f._.js")
R.c("server/chunks/ssr/[root-of-the-server]__33b8c640._.js")
R.c("server/chunks/ssr/[root-of-the-server]__655f8d11._.js")
R.c("server/chunks/ssr/node_modules_next_dist_f9713a08._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/_5f915289._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_programs_[slug]_page_actions_ddcc32bc.js")
R.m(3197)
module.exports=R.m(3197).exports
